/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package articles;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vendeurs.vendeur;

/**
 *
 * @author Hichem
 */
public class article extends javax.swing.JFrame {

    /**
     * Creates new form article
     */
    public article() {
        initComponents();
          filltable();
          filltotal();
          fillcombofour();
          fillcombotype();
          fillcombocat();
          resizejtable(jTablelistearticle);
          jButtonenregistrer.setEnabled(false);
          jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
          jButtonimprimer.setEnabled(true);
          jButtonexcel.setEnabled(true);
          jButtonnouveau.setText("Nouveau");
          cleararticle();
          jTablelistearticle.setEnabled(true);

          resetbutton();
         /* jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
          jButtonimprimer.setEnabled(false);
          jButtonexcel.setEnabled(false);
          */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldcodearticle = new javax.swing.JTextField();
        jTextFielddesignation = new javax.swing.JTextField();
        jTextFieldachat = new javax.swing.JTextField();
        jTextFieldvente = new javax.swing.JTextField();
        jTextFieldtva = new javax.swing.JTextField();
        jTextFieldstock = new javax.swing.JTextField();
        jComboBoxfour = new javax.swing.JComboBox();
        jComboBoxtype = new javax.swing.JComboBox();
        jComboBoxcat = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButtonnouveau = new javax.swing.JButton();
        jButtonmodifier = new javax.swing.JButton();
        jButtonsupprimer = new javax.swing.JButton();
        jButtonenregistrer = new javax.swing.JButton();
        jButtonimprimer = new javax.swing.JButton();
        jButtonexcel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelistearticle = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonfirst = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButtonnext = new javax.swing.JButton();
        jButtonlast = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldrecherche = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabeltotalarticle = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabeltotalachat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabeltotalvente = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/edit article 64.png"))); // NOI18N
        jLabel4.setText("Edition des Articles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Code article");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Designation");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Prix achat");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Prix vente");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Stock");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fournisseur");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TVA");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Categorie");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Type");

        jTextFieldcodearticle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldcodearticle.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFielddesignation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldachat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldachat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldvente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldtva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldtva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldtva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtvaActionPerformed(evt);
            }
        });

        jTextFieldstock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldstock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jComboBoxfour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxfour.setPreferredSize(new java.awt.Dimension(6, 20));
        jComboBoxfour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxfourMouseClicked(evt);
            }
        });
        jComboBoxfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxfourActionPerformed(evt);
            }
        });

        jComboBoxtype.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxtype.setPreferredSize(new java.awt.Dimension(6, 20));
        jComboBoxtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxtypeMouseClicked(evt);
            }
        });
        jComboBoxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtypeActionPerformed(evt);
            }
        });

        jComboBoxcat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxcat.setPreferredSize(new java.awt.Dimension(6, 20));
        jComboBoxcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxcatMouseClicked(evt);
            }
        });
        jComboBoxcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldcodearticle)
                    .addComponent(jTextFielddesignation)
                    .addComponent(jTextFieldachat)
                    .addComponent(jTextFieldvente)
                    .addComponent(jTextFieldtva)
                    .addComponent(jTextFieldstock)
                    .addComponent(jComboBoxfour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxcat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcodearticle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFielddesignation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldachat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldvente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldtva, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldstock, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxfour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jComboBoxcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonnouveau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonnouveau.setForeground(new java.awt.Color(0, 51, 51));
        jButtonnouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/new 24.png"))); // NOI18N
        jButtonnouveau.setText("Nouveau");
        jButtonnouveau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnouveauActionPerformed(evt);
            }
        });

        jButtonmodifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonmodifier.setForeground(new java.awt.Color(0, 51, 51));
        jButtonmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/update 24.png"))); // NOI18N
        jButtonmodifier.setText("Modifier");
        jButtonmodifier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonmodifier.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodifierActionPerformed(evt);
            }
        });

        jButtonsupprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonsupprimer.setForeground(new java.awt.Color(0, 51, 51));
        jButtonsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/delete 24.png"))); // NOI18N
        jButtonsupprimer.setText("Supprimer");
        jButtonsupprimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonsupprimer.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonsupprimer.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupprimerActionPerformed(evt);
            }
        });

        jButtonenregistrer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonenregistrer.setForeground(new java.awt.Color(0, 51, 51));
        jButtonenregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/save 24.png"))); // NOI18N
        jButtonenregistrer.setText("Enregistrer");
        jButtonenregistrer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonenregistrer.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonenregistrerActionPerformed(evt);
            }
        });

        jButtonimprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonimprimer.setForeground(new java.awt.Color(0, 51, 51));
        jButtonimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/print 24.png"))); // NOI18N
        jButtonimprimer.setText("Imprimer");
        jButtonimprimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonexcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonexcel.setForeground(new java.awt.Color(0, 51, 51));
        jButtonexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/excel 24.png"))); // NOI18N
        jButtonexcel.setText("Excel");
        jButtonexcel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonnouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonmodifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonenregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonimprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
            .addComponent(jButtonexcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonenregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonimprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTablelistearticle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablelistearticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "code article", "Designation", "Prix achat", "Prix vente", "TVA", "Stock", "Fournisseur", "Type", "Categorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelistearticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablelistearticleMouseClicked(evt);
            }
        });
        jTablelistearticle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTablelistearticleFocusGained(evt);
            }
        });
        jTablelistearticle.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTablelistearticleAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTablelistearticle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablelistearticleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablelistearticleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablelistearticle);
        if (jTablelistearticle.getColumnModel().getColumnCount() > 0) {
            jTablelistearticle.getColumnModel().getColumn(0).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(1).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(2).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(3).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(4).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(5).setResizable(false);
            jTablelistearticle.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonfirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonfirst.setForeground(new java.awt.Color(0, 102, 102));
        jButtonfirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/first 32.png"))); // NOI18N
        jButtonfirst.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfirstActionPerformed(evt);
            }
        });

        jButtonback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonback.setForeground(new java.awt.Color(0, 102, 102));
        jButtonback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/back 32.png"))); // NOI18N
        jButtonback.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jButtonnext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonnext.setForeground(new java.awt.Color(0, 102, 102));
        jButtonnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/next 32.png"))); // NOI18N
        jButtonnext.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnextActionPerformed(evt);
            }
        });

        jButtonlast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonlast.setForeground(new java.awt.Color(0, 102, 102));
        jButtonlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/last 32.png"))); // NOI18N
        jButtonlast.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlastActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deplacement");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonfirst, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonback, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButtonnext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonlast, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonfirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonnext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonlast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setPreferredSize(new java.awt.Dimension(251, 49));

        jTextFieldrecherche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrechercheActionPerformed(evt);
            }
        });
        jTextFieldrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/search 32.png"))); // NOI18N
        jLabel3.setText("Recherche");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(jTextFieldrecherche)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Infos Article");

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre Total d'Articles");

        jLabeltotalarticle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltotalarticle.setForeground(new java.awt.Color(153, 0, 51));
        jLabeltotalarticle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Prix Achat Total");

        jLabeltotalachat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltotalachat.setForeground(new java.awt.Color(153, 0, 51));
        jLabeltotalachat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Prix vente Total");

        jLabeltotalvente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltotalvente.setForeground(new java.awt.Color(153, 0, 51));
        jLabeltotalvente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltotalarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltotalachat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltotalvente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addComponent(jLabeltotalarticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltotalachat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltotalvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/liste article 63.png"))); // NOI18N
        jLabel17.setText("Liste d'Artciles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupprimerActionPerformed
        // TODO add your handling code here:
        
               int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de Supprimer cet Article","Supprimer Article",JOptionPane.YES_NO_OPTION);
       if(res==0){
           System.out.println("Article Supprime");
   
       }
        
    }//GEN-LAST:event_jButtonsupprimerActionPerformed

    private void jTextFieldtvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtvaActionPerformed

    private void jTextFieldrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrechercheActionPerformed
        // TODO add your handling code here:
        String x=jTextFieldrecherche.getText();
        if (x.length()>0 ){
        cleartable(jTablelistearticle);
        filltable(x);
        resetdeplacement();
        
        
        
        
        } else {
            cleartable(jTablelistearticle);
            filltable();
            resetdeplacement();
            
        }

        
    }//GEN-LAST:event_jTextFieldrechercheActionPerformed

    private void jButtonenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonenregistrerActionPerformed
        // TODO add your handling code here:
     int code=Integer.parseInt(jTextFieldcodearticle.getText().toString());
     String des=jTextFielddesignation.getText().toString();
     Double achat=Double.parseDouble(jTextFieldachat.getText().toString());
     Double vente=Double.parseDouble(jTextFieldvente.getText().toString());
     int tva= Integer.parseInt(jTextFieldtva.getText().toString());
     int stock=Integer.parseInt(jTextFieldstock.getText().toString());
     String four=jComboBoxfour.getSelectedItem().toString();
     String type=jComboBoxtype.getSelectedItem().toString();
     String cat=jComboBoxcat.getSelectedItem().toString();
     
 
     try {
            // TODO add your handling code here:
            Connection con;
            PreparedStatement pst;
            Statement st;
            ResultSet rs;
            
      
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", ""); 
            String query = "insert into article(codearticle,designationarticle,prixachat,prixvente,tva,stock,codefournisseur,typearticle,categoriearticle) values(?,?,?,?,?,?,?,?,?)";           
            pst = con.prepareStatement(query);
            pst.setInt(1,code);
            pst.setString(2,des);
            pst.setDouble(3, achat);
            pst.setDouble(4,vente);
            pst.setInt(5,tva);
            pst.setInt(6, stock);
           
            pst.setString(8,type);
            pst.setString(9, cat);
           query="SELECT codefournisseur from fournisseur WHERE nomfournisseur='"+four+"'";
           st=con.createStatement();
           rs=st.executeQuery(query);
           while(rs.next()){
            pst.setInt(7,rs.getInt(1));
           }
            int res=pst.executeUpdate();
            
          
              
     }
     catch (Exception e){
      System.out.println("ERROR DATABASE:  " +e);
     }
    
     //cleartable(jTablelistearticle);
     //filltable();
  
    filltable();
    filltotal();
    resetbutton();
    //cleararticle();
    jTextFieldcodearticle.setText("");
    jButtonenregistrer.setEnabled(false);
    jButtonnouveau.setEnabled(true);
    jTablelistearticle.setEnabled(true);
    
    }//GEN-LAST:event_jButtonenregistrerActionPerformed

    public void cleararticle(){
              jTextFieldcodearticle.setText("");
          jTextFielddesignation.setText("");
          jTextFieldachat.setText(""); 
          jTextFieldvente.setText("");
          jTextFieldtva.setText("");
          jTextFieldstock.setText("");    
    
    }
    
    
    private void jButtonnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnouveauActionPerformed
        // TODO add your handling code here:
         if(jButtonnouveau.getText().equals("Nouveau")){
          jButtonenregistrer.setEnabled(true);
          jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
          jButtonimprimer.setEnabled(false);
          jButtonexcel.setEnabled(false);
          jButtonnouveau.setText("Annuler");
          cleararticle();
          jTablelistearticle.setEnabled(false);
        }
        else    
     resetbutton();
    }//GEN-LAST:event_jButtonnouveauActionPerformed

    public void resetbutton(){
if(jButtonnouveau.getText().equals("Annuler")) {
          jButtonenregistrer.setEnabled(false);
          jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
          jButtonimprimer.setEnabled(true);
          jButtonexcel.setEnabled(true);
          jButtonnouveau.setText("Nouveau");
          cleararticle();
          jTablelistearticle.setEnabled(true);
  
        }    
     
    }
    
    
    
    private void jComboBoxfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxfourActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jComboBoxfourActionPerformed

    private void jComboBoxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxtypeActionPerformed

    private void jComboBoxcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcatActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxcatActionPerformed

    private void jComboBoxfourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxfourMouseClicked
        // TODO add your handling code here:
        jComboBoxfour.removeAllItems();
        fillcombofour();
    }//GEN-LAST:event_jComboBoxfourMouseClicked

    private void jComboBoxtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxtypeMouseClicked
        // TODO add your handling code here:
        jComboBoxtype.removeAllItems();
        fillcombotype();
    }//GEN-LAST:event_jComboBoxtypeMouseClicked

    private void jComboBoxcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxcatMouseClicked
        // TODO add your handling code here:
        jComboBoxcat.removeAllItems();
        fillcombocat();
    }//GEN-LAST:event_jComboBoxcatMouseClicked

    private void jTablelistearticleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTablelistearticleAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTablelistearticleAncestorAdded

    private void jTablelistearticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablelistearticleMouseClicked
        // TODO add your handling code here:
fillinfoarticle();
          
    }//GEN-LAST:event_jTablelistearticleMouseClicked
public void fillinfoarticle(){
    DefaultTableModel model =   (DefaultTableModel)jTablelistearticle.getModel();
    
     int i=jTablelistearticle.getSelectedRow();
     if(i>-1){
     jTextFieldcodearticle.setText(model.getValueAt(i,0).toString());
     jTextFielddesignation.setText(model.getValueAt(i,1).toString());
     jTextFieldachat.setText(model.getValueAt(i,2).toString());
     jTextFieldvente.setText(model.getValueAt(i,3).toString());
     jTextFieldtva.setText(model.getValueAt(i,4).toString());
     jTextFieldstock.setText(model.getValueAt(i,5).toString());
     jComboBoxfour.setSelectedItem(model.getValueAt(i,6).toString());
     jComboBoxtype.setSelectedItem(model.getValueAt(i,7).toString());
     jComboBoxcat.setSelectedItem(model.getValueAt(i,8).toString());
     
          jTablelistearticle.setEnabled(true);
          resetbutton();
          jButtonmodifier.setEnabled(true);
          jButtonsupprimer.setEnabled(true);

     }
}
    
    
    
    private void jTablelistearticleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablelistearticleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablelistearticleFocusGained

    private void jTablelistearticleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelistearticleKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTablelistearticleKeyPressed

    private void jTablelistearticleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelistearticleKeyReleased
        // TODO add your handling code here:
                            DefaultTableModel model =   (DefaultTableModel)jTablelistearticle.getModel();
    
     int i=jTablelistearticle.getSelectedRow();
     jTextFieldcodearticle.setText(model.getValueAt(i,0).toString());
     jTextFielddesignation.setText(model.getValueAt(i,1).toString());
     jTextFieldachat.setText(model.getValueAt(i,2).toString());
     jTextFieldvente.setText(model.getValueAt(i,3).toString());
     jTextFieldtva.setText(model.getValueAt(i,4).toString());
     jTextFieldstock.setText(model.getValueAt(i,5).toString());
     jComboBoxfour.setSelectedItem(model.getValueAt(i,6).toString());
     jComboBoxtype.setSelectedItem(model.getValueAt(i,7).toString());
     jComboBoxcat.setSelectedItem(model.getValueAt(i,8).toString());          
     
     jTablelistearticle.setEnabled(true);
     resetbutton();
     jButtonmodifier.setEnabled(true);
     jButtonsupprimer.setEnabled(true);
     
    }//GEN-LAST:event_jTablelistearticleKeyReleased

    private void jTextFieldrechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheKeyTyped
        // TODO add your handling code here:
        
            String x=jTextFieldrecherche.getText();
        if (x.length()>0 ){
        cleartable(jTablelistearticle);
        filltable();
        filltotal();
        
        
        
        
        } else {
            cleartable(jTablelistearticle);
            filltable();
            filltotal();
        }    
    }//GEN-LAST:event_jTextFieldrechercheKeyTyped

    private void jTextFieldrechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldrechercheKeyPressed

    private void jTextFieldrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheKeyReleased
        // TODO add your handling code here:
                String x=jTextFieldrecherche.getText();
        if (x.length()>0 ){
        cleartable(jTablelistearticle);
        filltable(x);
        cleararticle();
        resetbutton();
        resetdeplacement();
          jTablelistearticle.setEnabled(true);
          jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
        
        
        } else {
            cleartable(jTablelistearticle);
            filltable();
            cleararticle();
          jTablelistearticle.setEnabled(true); 
          resetbutton();
          resetdeplacement();
          jButtonmodifier.setEnabled(false);
          jButtonsupprimer.setEnabled(false);
        }
        
    }//GEN-LAST:event_jTextFieldrechercheKeyReleased

    private void jButtonfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfirstActionPerformed
        // TODO add your handling code here:
        
        
        if (rowselected==false){
        rowselected=true;  
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistearticle.getModel();
        index=jTablelistearticle.getSelectedRow();
        if (index<=0){ 
        jTablelistearticle.setRowSelectionInterval(0,0);
        fillinfoarticle();
        jButtonback.setEnabled(false);
        jButtonfirst.setEnabled(false);
        }
        else{
        //model.moveRow(index, index, index-1);
        jTablelistearticle.setRowSelectionInterval(0, 0);
        fillinfoarticle();
        jButtonback.setEnabled(false);
        jButtonfirst.setEnabled(false);
        jButtonnext.setEnabled(true);
        jButtonlast.setEnabled(true);
        }
        
        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);
                                  
        
                         
    }//GEN-LAST:event_jButtonfirstActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
    if (rowselected==false){
        rowselected=true;  
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistearticle.getModel();
        index=jTablelistearticle.getSelectedRow();
        if (index<=0){ 
        jTablelistearticle.setRowSelectionInterval(0,0);
        fillinfoarticle();
        jButtonback.setEnabled(false);
        jButtonfirst.setEnabled(false);
        }
        else{
        //model.moveRow(index, index, index-1);
        jTablelistearticle.setRowSelectionInterval(index-1, index-1);
        fillinfoarticle();
        jButtonnext.setEnabled(true);
        jButtonlast.setEnabled(true);
        }
        
        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);
                                  
        
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodifierActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model =   (DefaultTableModel)jTablelistearticle.getModel();
    
     int i=jTablelistearticle.getSelectedRow();
     if(i>-1){
         jButtonmodifier.setEnabled(true);
        
        int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de modifier cet Article","Modifier Article",JOptionPane.YES_NO_OPTION);
      
       
       if(res==0){
           System.out.println("Article modifie");
   
       }
     }else {JOptionPane.showMessageDialog(this, "Selectionner un produit SVP");}
               
               
    }//GEN-LAST:event_jButtonmodifierActionPerformed
        boolean rowselected=false;
        int index;
        
    private void jButtonnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnextActionPerformed
        // TODO add your handling code here:

        
        if (rowselected==false){
        rowselected=true;  
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistearticle.getModel();
        index=jTablelistearticle.getSelectedRow();
        
         if(index==jTablelistearticle.getRowCount()-1){
            jButtonnext.setEnabled(false);
            jButtonlast.setEnabled(false);
        }
        if (index==-1){ 
            jTablelistearticle.setRowSelectionInterval(0,0);
            fillinfoarticle();
            jButtonback.setEnabled(false);
            jButtonfirst.setEnabled(false);
        
        }
        
        else {
            if(index==jTablelistearticle.getRowCount()-1){
            jButtonnext.setEnabled(false);
            jButtonlast.setEnabled(false);}else
            {  
        //model.moveRow(index, index, index+1);
        jTablelistearticle.setRowSelectionInterval(index+1, index+1);
        fillinfoarticle();
        jButtonback.setEnabled(true);
        jButtonfirst.setEnabled(true);
            }
        }

        
        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);
        
        
    }//GEN-LAST:event_jButtonnextActionPerformed

    private void jButtonlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlastActionPerformed
        // TODO add your handling code here:
                if (rowselected==false){
        rowselected=true;  
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistearticle.getModel();
        index=jTablelistearticle.getSelectedRow();
        if (index<=0){ 
        jTablelistearticle.setRowSelectionInterval(jTablelistearticle.getRowCount()-1,jTablelistearticle.getRowCount()-1);
        fillinfoarticle();
        jButtonback.setEnabled(true);
        jButtonfirst.setEnabled(true);
        jButtonnext.setEnabled(false);
        jButtonlast.setEnabled(false);
        }
        else{
        //model.moveRow(index, index, index-1);
        jTablelistearticle.setRowSelectionInterval(jTablelistearticle.getRowCount()-1, jTablelistearticle.getRowCount()-1);
        fillinfoarticle();
        jButtonback.setEnabled(true);
        jButtonfirst.setEnabled(true);
        jButtonnext.setEnabled(false);
        jButtonlast.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonlastActionPerformed

  public void filltotal(){
   int a;   
   Float b,c;
   Connection con;
   Statement st1,st2,st3;
   ResultSet rs1,rs2,rs3;
   
   String query1="SELECT count(*) from article";
   String query2="SELECT SUM(prixachat) from article";
   String query3="SELECT SUM(prixvente) from article";
         try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st1=con.createStatement();
            st2=con.createStatement();
            st3=con.createStatement();
            rs1=st1.executeQuery(query1);
            rs2=st2.executeQuery(query2);
            rs3=st3.executeQuery(query3);
   
      while(rs1.next()){
          a=rs1.getInt(1); 
   jLabeltotalarticle.setText(""+a);

      }
      
      while(rs2.next()){
          b=rs2.getFloat(1); 
   jLabeltotalachat.setText(b.toString());

      }
      while(rs3.next()){
          c=rs3.getFloat(1); 
   jLabeltotalvente.setText(c.toString());

      }      
      
         }
         catch(Exception e){
             System.out.println(" ERROR DATABASE"+e);
         }
      
  }
    
    public void resetdeplacement(){
        jButtonback.setEnabled(true);
        jButtonfirst.setEnabled(true);
        jButtonnext.setEnabled(true);
        jButtonlast.setEnabled(true);
        
        
        
    }
    
    
     public void fillcombofour(){
     Connection con;
        Statement st;
        ResultSet rs;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String query ="SELECT nomfournisseur from fournisseur ";
 
            rs=st.executeQuery(query);
            
            
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxfour.addItem(rs.getString("nomfournisseur"));
                
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }    
        
    }
    

     public void fillcombotype(){
     Connection con;
        Statement st;
        ResultSet rs;
            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String query ="SELECT nomtype from type ";
            rs=st.executeQuery(query);
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxtype.addItem(rs.getString("nomtype"));
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }     
    }     
     
     public void fillcombocat(){
     Connection con;
        Statement st;
        ResultSet rs;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String query ="SELECT nomcategorie from categorie ";
 
            rs=st.executeQuery(query);
            
            
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxcat.addItem(rs.getString("nomcategorie"));
                
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }    
        
    }
     
     
     
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new article().setVisible(true);
                
            }
        });
        
      
    }
  public void resizejtable(JTable table){
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(300);
        table.getColumnModel().getColumn(2).setPreferredWidth(90);
        table.getColumnModel().getColumn(3).setPreferredWidth(90);
        table.getColumnModel().getColumn(4).setPreferredWidth(60);
        table.getColumnModel().getColumn(5).setPreferredWidth(60);
        table.getColumnModel().getColumn(6).setPreferredWidth(190);
        table.getColumnModel().getColumn(7).setPreferredWidth(140);
        table.getColumnModel().getColumn(8).setPreferredWidth(140);
        
    }
 
public void cleartable(JTable table){
DefaultTableModel model =(DefaultTableModel)table.getModel();
     


                while (table.getRowCount() > 0) {
                    ((DefaultTableModel) table.getModel()).removeRow(0);
                }
                /*
     for(int i=0;i<model.getRowCount();i++){
 model.removeRow(i);
 System.out.println(i);
     }*/
                
    }  
  
    public void filltable(){
     
        cleartable(jTablelistearticle);
        
        DefaultTableModel model =   (DefaultTableModel)jTablelistearticle.getModel();
        Object[] row = new Object[9];
        
        
        
        
        Connection con;
        Statement st,st1;
        ResultSet rs,rs1;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            String query1;
            String query="select * from article";
                rs = st.executeQuery(query);
                while(rs.next()){
                     row[0] = rs.getInt(1);
                     row[1] = rs.getString(2);
                     row[2] = rs.getString(3);
                     row[3] = rs.getString(4);
                     row[4] = rs.getInt(5);
                     row[5] = rs.getInt(6);
                  
                     row[7] = rs.getString(8);
                     row[8] = rs.getString(9);
                     query1="select nomfournisseur from fournisseur where codefournisseur="+rs.getInt(7);
                     rs1 = st1.executeQuery(query1);
                     while(rs1.next()){
                     row[6] = rs1.getString(1);
                     }
                     model.addRow(row);
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    }
    
    
    public void filltable(String x){
     
        cleartable(jTablelistearticle);
        
        DefaultTableModel model =   (DefaultTableModel)jTablelistearticle.getModel();
        Object[] row = new Object[9];
        
        
        
        
        Connection con;
        Statement st,st1;
        ResultSet rs,rs1;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            String query1;
            String query="select * from article WHERE codearticle LIKE '%"+x+"%' OR designationarticle LIKE '%"+x+"%'";
                rs = st.executeQuery(query);
                while(rs.next()){
                     row[0] = rs.getInt(1);
                     row[1] = rs.getString(2);
                     row[2] = rs.getString(3);
                     row[3] = rs.getString(4);
                     row[4] = rs.getInt(5);
                     row[5] = rs.getInt(6);
                  
                     row[7] = rs.getString(8);
                     row[8] = rs.getString(9);
                     query1="select nomfournisseur from fournisseur where codefournisseur="+rs.getInt(7);
                     rs1 = st1.executeQuery(query1);
                     while(rs1.next()){
                     row[6] = rs1.getString(1);
                     }
                     model.addRow(row);
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    }
    
    
    
    public String setvirgule(Double d, int n){
   
    NumberFormat virgule = NumberFormat.getInstance(); 
    virgule.setMinimumFractionDigits(n);       //Nb de Digit mini 
    virgule.setMaximumFractionDigits(n);       //Nb de Digit Maxi 
    return(virgule.format(d));  //Formatage str="12.45" 
     
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonenregistrer;
    private javax.swing.JButton jButtonexcel;
    private javax.swing.JButton jButtonfirst;
    private javax.swing.JButton jButtonimprimer;
    private javax.swing.JButton jButtonlast;
    private javax.swing.JButton jButtonmodifier;
    private javax.swing.JButton jButtonnext;
    private javax.swing.JButton jButtonnouveau;
    private javax.swing.JButton jButtonsupprimer;
    private javax.swing.JComboBox jComboBoxcat;
    private javax.swing.JComboBox jComboBoxfour;
    private javax.swing.JComboBox jComboBoxtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeltotalachat;
    private javax.swing.JLabel jLabeltotalarticle;
    private javax.swing.JLabel jLabeltotalvente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelistearticle;
    private javax.swing.JTextField jTextFieldachat;
    private javax.swing.JTextField jTextFieldcodearticle;
    private javax.swing.JTextField jTextFielddesignation;
    private javax.swing.JTextField jTextFieldrecherche;
    private javax.swing.JTextField jTextFieldstock;
    private javax.swing.JTextField jTextFieldtva;
    private javax.swing.JTextField jTextFieldvente;
    // End of variables declaration//GEN-END:variables
}
