/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hichem
 */
public class vente extends javax.swing.JFrame {

    /**
     * Creates new form vente
     */
    public vente() {
        initComponents();
        filltable(jTablelistevente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldrecherchevente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonfirstvente = new javax.swing.JButton();
        jButtonbackvente = new javax.swing.JButton();
        jButtonnextvente = new javax.swing.JButton();
        jButtonlastvente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonmodifiervente = new javax.swing.JButton();
        jButtonsupprimervente = new javax.swing.JButton();
        jButtonimprimervente = new javax.swing.JButton();
        jButtonexcelvente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabelnbrtotalvente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabeltotaltva = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabeltotalvente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelistevente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 680));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/edit article 64.png"))); // NOI18N
        jLabel4.setText("Edition des ventes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/liste article 63.png"))); // NOI18N
        jLabel17.setText("Liste de Ventes");

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setPreferredSize(new java.awt.Dimension(251, 49));

        jTextFieldrecherchevente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldrecherchevente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrechercheventeActionPerformed(evt);
            }
        });
        jTextFieldrecherchevente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheventeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheventeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheventeKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/search 32.png"))); // NOI18N
        jLabel3.setText("Recherche");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldrecherchevente, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(jTextFieldrecherchevente)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonfirstvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonfirstvente.setForeground(new java.awt.Color(0, 102, 102));
        jButtonfirstvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/first 32.png"))); // NOI18N
        jButtonfirstvente.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonfirstvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfirstventeActionPerformed(evt);
            }
        });

        jButtonbackvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonbackvente.setForeground(new java.awt.Color(0, 102, 102));
        jButtonbackvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/back 32.png"))); // NOI18N
        jButtonbackvente.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonbackvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackventeActionPerformed(evt);
            }
        });

        jButtonnextvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonnextvente.setForeground(new java.awt.Color(0, 102, 102));
        jButtonnextvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/next 32.png"))); // NOI18N
        jButtonnextvente.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonnextvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnextventeActionPerformed(evt);
            }
        });

        jButtonlastvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonlastvente.setForeground(new java.awt.Color(0, 102, 102));
        jButtonlastvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/last 32.png"))); // NOI18N
        jButtonlastvente.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonlastvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlastventeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deplacement");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonfirstvente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonbackvente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonnextvente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonlastvente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonfirstvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonbackvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonnextvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonlastvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonmodifiervente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonmodifiervente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonmodifiervente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/update 24.png"))); // NOI18N
        jButtonmodifiervente.setText("Modifier");
        jButtonmodifiervente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonmodifiervente.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonmodifiervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodifierventeActionPerformed(evt);
            }
        });

        jButtonsupprimervente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonsupprimervente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonsupprimervente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/delete 24.png"))); // NOI18N
        jButtonsupprimervente.setText("Supprimer");
        jButtonsupprimervente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonsupprimervente.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonsupprimervente.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonsupprimervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupprimerventeActionPerformed(evt);
            }
        });

        jButtonimprimervente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonimprimervente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonimprimervente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/print 24.png"))); // NOI18N
        jButtonimprimervente.setText("Imprimer");
        jButtonimprimervente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonexcelvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonexcelvente.setForeground(new java.awt.Color(0, 51, 51));
        jButtonexcelvente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/excel 24.png"))); // NOI18N
        jButtonexcelvente.setText("Excel");
        jButtonexcelvente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonmodifiervente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonsupprimervente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonimprimervente, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(jButtonexcelvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonmodifiervente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonsupprimervente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonexcelvente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonimprimervente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre Total de Ventes");

        jLabelnbrtotalvente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelnbrtotalvente.setForeground(new java.awt.Color(153, 0, 51));
        jLabelnbrtotalvente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Total TVA");

        jLabeltotaltva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltotaltva.setForeground(new java.awt.Color(153, 0, 51));
        jLabeltotaltva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Prix vente Total");

        jLabeltotalvente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeltotalvente.setForeground(new java.awt.Color(153, 0, 51));
        jLabeltotalvente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnbrtotalvente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltotaltva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltotalvente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addComponent(jLabelnbrtotalvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltotaltva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabeltotalvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTablelistevente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablelistevente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caissier", "code vente", "Date vente", "Heure vente", "designation article", "Quantite", "prix artcile", "prix total articles", "Total tva", "Total Vente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelistevente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablelisteventeMouseClicked(evt);
            }
        });
        jTablelistevente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTablelisteventeFocusGained(evt);
            }
        });
        jTablelistevente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTablelisteventeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTablelistevente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablelisteventeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablelisteventeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablelistevente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldrechercheventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrechercheventeActionPerformed
        // TODO add your handling code here:
        String x=jTextFieldrecherchevente.getText();
        if (x.length()>0 ){
            cleartable(jTablelistevente);
            filltable(x);
            resetdeplacement();

        } else {
            cleartable(jTablelistevente);
            filltable(jTablelistevente);
            resetdeplacement();

        }

    }//GEN-LAST:event_jTextFieldrechercheventeActionPerformed
     public void resetdeplacement(){
        jButtonbackvente.setEnabled(true);
        jButtonfirstvente.setEnabled(true);
        jButtonnextvente.setEnabled(true);
        jButtonlastvente.setEnabled(true);              
    }
    
    
    
    
    private void jTextFieldrechercheventeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheventeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldrechercheventeKeyPressed

 public void cleartable(JTable table){
DefaultTableModel model =(DefaultTableModel)table.getModel();
                while (table.getRowCount() > 0) {
                    ((DefaultTableModel) table.getModel()).removeRow(0);
                }
                /*
     for(int i=0;i<model.getRowCount();i++){
 model.removeRow(i);
 System.out.println(i);
     }*/             
    }    
    
    
    
    private void jTextFieldrechercheventeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheventeKeyReleased
        // TODO add your handling code here:
        String x=jTextFieldrecherchevente.getText();
        if (x.length()>0 ){
            cleartable(jTablelistevente);
            filltable(x);
            resetbutton();
            resetdeplacement();
            jTablelistevente.setEnabled(true);
            jButtonmodifiervente.setEnabled(false);
            jButtonsupprimervente.setEnabled(false);

        } else {
            cleartable(jTablelistevente);
            filltable(jTablelistevente);
            jTablelistevente.setEnabled(true);
            resetbutton();
            resetdeplacement();
            jButtonmodifiervente.setEnabled(false);
            jButtonsupprimervente.setEnabled(false);
        }

    }//GEN-LAST:event_jTextFieldrechercheventeKeyReleased

       public void resetbutton(){


          jButtonmodifiervente.setEnabled(false);
          jButtonsupprimervente.setEnabled(false);
          jButtonimprimervente.setEnabled(true);
          jButtonexcelvente.setEnabled(true);
     
          //clearvente();
          jTablelistevente.setEnabled(true); 
    }  
    
    
    private void jTextFieldrechercheventeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheventeKeyTyped
        // TODO add your handling code here:

        String x=jTextFieldrecherchevente.getText();
        if (x.length()>0 ){
            cleartable(jTablelistevente);
            filltable(x);
           // filltotal();

        } else {
            cleartable(jTablelistevente);
            filltable(jTablelistevente);
            //filltotal();
        }
    }//GEN-LAST:event_jTextFieldrechercheventeKeyTyped

    private void jButtonfirstventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfirstventeActionPerformed
        // TODO add your handling code here:

        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistevente.getModel();
        index=jTablelistevente.getSelectedRow();
        if (index<=0){
            jTablelistevente.setRowSelectionInterval(0,0);
            //fillinfovente();
            jButtonbackvente.setEnabled(false);
            jButtonfirstvente.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelistevente.setRowSelectionInterval(0, 0);
            //fillinfovente();
            jButtonbackvente.setEnabled(false);
            jButtonfirstvente.setEnabled(false);
            jButtonnextvente.setEnabled(true);
            jButtonlastvente.setEnabled(true);
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonfirstventeActionPerformed

    private void jButtonbackventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackventeActionPerformed
        // TODO add your handling code here:
        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistevente.getModel();
        index=jTablelistevente.getSelectedRow();
        if (index<=0){
            jTablelistevente.setRowSelectionInterval(0,0);
            //fillinfovente();
            jButtonbackvente.setEnabled(false);
            jButtonfirstvente.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelistevente.setRowSelectionInterval(index-1, index-1);
            //fillinfovente();
            jButtonnextvente.setEnabled(true);
            jButtonlastvente.setEnabled(true);
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonbackventeActionPerformed

    private void jButtonnextventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnextventeActionPerformed
        // TODO add your handling code here:

        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistevente.getModel();
        index=jTablelistevente.getSelectedRow();

        if(index==jTablelistevente.getRowCount()-1){
            jButtonnextvente.setEnabled(false);
            jButtonlastvente.setEnabled(false);
        }
        if (index==-1){
            jTablelistevente.setRowSelectionInterval(0,0);
            //fillinfovente();
            jButtonbackvente.setEnabled(false);
            jButtonfirstvente.setEnabled(false);

        }

        else {
            if(index==jTablelistevente.getRowCount()-1){
                jButtonnextvente.setEnabled(false);
                jButtonlastvente.setEnabled(false);}else
            {
                //model.moveRow(index, index, index+1);
                jTablelistevente.setRowSelectionInterval(index+1, index+1);
                //fillinfovente();
                jButtonbackvente.setEnabled(true);
                jButtonfirstvente.setEnabled(true);
            }
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonnextventeActionPerformed
int index;
boolean rowselected=false;
    private void jButtonlastventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlastventeActionPerformed
        // TODO add your handling code here:
        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelistevente.getModel();
        index=jTablelistevente.getSelectedRow();
        if (index<=0){
            jTablelistevente.setRowSelectionInterval(jTablelistevente.getRowCount()-1,jTablelistevente.getRowCount()-1);
            //fillinfovente();
            jButtonbackvente.setEnabled(true);
            jButtonfirstvente.setEnabled(true);
            jButtonnextvente.setEnabled(false);
            jButtonlastvente.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelistevente.setRowSelectionInterval(jTablelistevente.getRowCount()-1, jTablelistevente.getRowCount()-1);
            //fillinfovente();
            jButtonbackvente.setEnabled(true);
            jButtonfirstvente.setEnabled(true);
            jButtonnextvente.setEnabled(false);
            jButtonlastvente.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonlastventeActionPerformed

    private void jButtonmodifierventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodifierventeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =   (DefaultTableModel)jTablelistevente.getModel();

        int i=jTablelistevente.getSelectedRow();
        if(i>-1){
            jButtonmodifiervente.setEnabled(true);

            int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de modifier cette vente","Modifier vente",JOptionPane.YES_NO_OPTION);

            if(res==0){
                System.out.println("vente modifiee");

            }
        }else {JOptionPane.showMessageDialog(this, "Selectionner un produit SVP");}

    }//GEN-LAST:event_jButtonmodifierventeActionPerformed

    private void jButtonsupprimerventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupprimerventeActionPerformed
        // TODO add your handling code here:

        int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de Supprimer cette vente","Supprimer Vente",JOptionPane.YES_NO_OPTION);
        if(res==0){
            System.out.println("vente Supprimee");

        }

    }//GEN-LAST:event_jButtonsupprimerventeActionPerformed

    private void jTablelisteventeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablelisteventeMouseClicked
        // TODO add your handling code here:
        //fillinfovente();

    }//GEN-LAST:event_jTablelisteventeMouseClicked

    private void jTablelisteventeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablelisteventeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablelisteventeFocusGained

    private void jTablelisteventeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTablelisteventeAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTablelisteventeAncestorAdded

    private void jTablelisteventeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelisteventeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablelisteventeKeyPressed

    private void jTablelisteventeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelisteventeKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model =   (DefaultTableModel)jTablelistevente.getModel();

        int i=jTablelistevente.getSelectedRow();
     /*   jTextFieldcodearticle.setText(model.getValueAt(i,0).toString());
        jTextFielddesignation.setText(model.getValueAt(i,1).toString());
        jTextFieldachat.setText(model.getValueAt(i,2).toString());
        jTextFieldvente.setText(model.getValueAt(i,3).toString());
        jTextFieldtva.setText(model.getValueAt(i,4).toString());
        jTextFieldstock.setText(model.getValueAt(i,5).toString());
        jComboBoxfour.setSelectedItem(model.getValueAt(i,6).toString());
        jComboBoxtype.setSelectedItem(model.getValueAt(i,7).toString());
        jComboBoxcat.setSelectedItem(model.getValueAt(i,8).toString());
*/
        jTablelistevente.setEnabled(true);
        resetbutton();
        jButtonmodifiervente.setEnabled(true);
        jButtonsupprimervente.setEnabled(true);

    }//GEN-LAST:event_jTablelisteventeKeyReleased

public void filltable(String x){    
        cleartable(jTablelistevente);
        DefaultTableModel model =   (DefaultTableModel)jTablelistevente.getModel();
        Object[] row = new Object[10];
        Connection con;
        Statement st,st1,st2;
        ResultSet rs,rs1,rs2;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            st2=con.createStatement();
            String query1,query2;
            String query="select * from vente where  codevente LIKE '%"+x+"%' OR date LIKE '%"+x+"%'OR time LIKE '%"+x+"%' OR date username '%"+x+"%'";
            
                rs = st.executeQuery(query);
                
                while(rs.next()){
                    query1="select * from detailsvente where codevente='"+rs.getInt(1)+"'";                 
                    rs1 = st1.executeQuery(query1);
                    
                    while (rs1.next()){
                     row[0] = rs.getString(6);
                     row[1] = rs.getInt(1);
                     row[2] = rs.getString(2);
                     row[3] = rs.getString(3);
                     row[8] = rs.getDouble(4);
                     row[9] = rs.getDouble(5);
                     row[5] = rs1.getInt(3);
                     query2="select * from article where codearticle='"+rs1.getInt(2)+"'";
                     rs2=st2.executeQuery(query2);
                     while(rs2.next()){
                     row[4] = rs2.getString(2);
                     row[6] = rs2.getDouble(4);
                     row[7] = (rs2.getDouble(4))*(rs1.getInt(3));
                     model.addRow(row);
                     }
                    }
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    } 
    
    
    
    

public void filltable(JTable table){    
        cleartable(jTablelistevente);
        DefaultTableModel model =   (DefaultTableModel)table.getModel();
        Object[] row = new Object[10];
        Connection con;
        Statement st,st1,st2;
        ResultSet rs,rs1,rs2;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            st2=con.createStatement();
            String query1,query2;
            String query="select * from vente";
            
                rs = st.executeQuery(query);
                
                while(rs.next()){
                    query1="select * from detailsvente where codevente='"+rs.getInt(1)+"'";                 
                    rs1 = st1.executeQuery(query1);
                    
                    while (rs1.next()){
                     row[0] = rs.getString(6);
                     row[1] = rs.getInt(1);
                     row[2] = rs.getString(2);
                     row[3] = rs.getString(3);
                     row[8] = rs.getDouble(4);
                     row[9] = rs.getDouble(5);
                     row[5] = rs1.getInt(3);
                     query2="select * from article where codearticle='"+rs1.getInt(2)+"'";
                     rs2=st2.executeQuery(query2);
                     while(rs2.next()){
                     row[4] = rs2.getString(2);
                     row[6] = rs2.getDouble(4);
                     row[7] = rs2.getDouble(4)*rs1.getInt(3);
                     model.addRow(row);
                     }
                    }
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    }  
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbackvente;
    private javax.swing.JButton jButtonexcelvente;
    private javax.swing.JButton jButtonfirstvente;
    private javax.swing.JButton jButtonimprimervente;
    private javax.swing.JButton jButtonlastvente;
    private javax.swing.JButton jButtonmodifiervente;
    private javax.swing.JButton jButtonnextvente;
    private javax.swing.JButton jButtonsupprimervente;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelnbrtotalvente;
    private javax.swing.JLabel jLabeltotaltva;
    private javax.swing.JLabel jLabeltotalvente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelistevente;
    private javax.swing.JTextField jTextFieldrecherchevente;
    // End of variables declaration//GEN-END:variables
}
