/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendeurs;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static org.eclipse.persistence.platform.database.oracle.plsql.OraclePLSQLTypes.Int;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import java.util.*;

/**
 *
 * @author Hichem
 */
public class vendeur extends javax.swing.JFrame {

    /**
     * Creates new form vendeur
     */
    
    public vendeur(String username) {
        initComponents();
        String strdate;
        //LocalDate.now(ZoneId.of( "France/Paris" ) ).format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT ).withLocale( Locale.CANADA );

        jButtonpanier.setEnabled(false);
        jButtonpayer.setEnabled(false);
        jButtonbonlivraison.setEnabled(false);
        jButtondevis.setEnabled(false);
        jButtonfacture.setEnabled(false);
        jButtonsupprimer.setEnabled(false);
        
        resizejtable(jTabledetailsvente);
       // strdate = new SimpleDateFormat("dd/MM/YYYY | hh:mm:ss",Locale.FRENCH).format(new Date());
         jLabelnomvendeur.setText(username);  //+"                  "+strdate);
         dynamicdate();
         fillcombo();
         fillcombocat();
         fillcombotype();
    }

    public vendeur() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    public void dynamicdate(){
        
       Thread clock=new Thread(){
         public void run(){
             for(;;){
        try{ 
        String strdate = new SimpleDateFormat("dd/MM/YYYY",Locale.FRENCH).format(new Date());
        String strtime = new SimpleDateFormat("HH:mm:ss",Locale.FRENCH).format(new Date()); 
        
         jLabeldate.setText( strdate+"     "+strtime);
         //jLabeltime.setText("Time:   "+strtime);
        }
        catch (Exception e){
            System.out.println("error"+e);
        }
             
         }  
           
         }  
   
       };
               clock.start();
        
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelvente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledetailsvente = new javax.swing.JTable();
        jButtonsupprimer = new javax.swing.JButton();
        jPanelpayer = new javax.swing.JPanel();
        jButtonpayer = new javax.swing.JButton();
        jLabeltimbre = new javax.swing.JLabel();
        jTextFieldmontanttva = new javax.swing.JTextField();
        jLabelmontanttva = new javax.swing.JLabel();
        jTextFieldtotalttc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldtimbre = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonfacture = new javax.swing.JButton();
        jButtonbonlivraison = new javax.swing.JButton();
        jButtondevis = new javax.swing.JButton();
        jPanelinfoarticle = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldcode = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFielddesignation = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldprixvente = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldstock = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldtva = new javax.swing.JTextField();
        jButtonpanier = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabelquantite = new javax.swing.JLabel();
        jTextFieldquantite = new javax.swing.JTextField();
        jLabelchercher = new javax.swing.JLabel();
        jTextFieldchercher = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxarticle = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxtype = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxcategorie = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelnomvendeur = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabeldate = new javax.swing.JLabel();
        jMenuBarvendeur = new javax.swing.JMenuBar();
        jMenuvendeurfichier = new javax.swing.JMenu();
        jMenubonretour = new javax.swing.JMenuItem();
        jMenurecette = new javax.swing.JMenuItem();
        jMenudeconnecter = new javax.swing.JMenuItem();
        jMenuvendeurediter = new javax.swing.JMenu();
        jMenuediterbon = new javax.swing.JMenuItem();
        jMenuediterdevis = new javax.swing.JMenuItem();
        jMenuediterfacture = new javax.swing.JMenuItem();
        jMenuvendeurimprimer = new javax.swing.JMenu();
        jMenuItembonlivraison = new javax.swing.JMenuItem();
        jMenudevis = new javax.swing.JMenuItem();
        jMenufacture = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendeur");
        setPreferredSize(new java.awt.Dimension(1390, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelvente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTabledetailsvente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabledetailsvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabledetailsvente.setForeground(new java.awt.Color(0, 0, 51));
        jTabledetailsvente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code article", "Désignation", "Prix Unitaire HT", "TVA", "Quantite", "Prix Total TTC", "Prix Total TTC H"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabledetailsvente.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTabledetailsvente.setRowHeight(25);
        jTabledetailsvente.getTableHeader().setReorderingAllowed(false);
        jTabledetailsvente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabledetailsventeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabledetailsventeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTabledetailsventeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTabledetailsvente);
        if (jTabledetailsvente.getColumnModel().getColumnCount() > 0) {
            jTabledetailsvente.getColumnModel().getColumn(0).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(1).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(2).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(3).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(4).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(5).setResizable(false);
            jTabledetailsvente.getColumnModel().getColumn(6).setResizable(false);
        }

        jButtonsupprimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonsupprimer.setForeground(new java.awt.Color(102, 0, 51));
        jButtonsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/remove basket 32.png"))); // NOI18N
        jButtonsupprimer.setText("Supprimer");
        jButtonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupprimerActionPerformed(evt);
            }
        });

        jPanelpayer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonpayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonpayer.setForeground(new java.awt.Color(153, 0, 0));
        jButtonpayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/pay 2.png"))); // NOI18N
        jButtonpayer.setText("PAYER");
        jButtonpayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpayerActionPerformed(evt);
            }
        });

        jLabeltimbre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeltimbre.setForeground(new java.awt.Color(102, 0, 51));
        jLabeltimbre.setText("Droit Timbre");

        jTextFieldmontanttva.setEditable(false);
        jTextFieldmontanttva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldmontanttva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldmontanttva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmontanttvaActionPerformed(evt);
            }
        });

        jLabelmontanttva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelmontanttva.setForeground(new java.awt.Color(102, 0, 51));
        jLabelmontanttva.setText("Montant tva");

        jTextFieldtotalttc.setEditable(false);
        jTextFieldtotalttc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldtotalttc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 51));
        jLabel10.setText("Totat TTC");

        jTextFieldtimbre.setEditable(false);
        jTextFieldtimbre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldtimbre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldtimbre.setText("0.600  TND");
        jTextFieldtimbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtimbreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelpayerLayout = new javax.swing.GroupLayout(jPanelpayer);
        jPanelpayer.setLayout(jPanelpayerLayout);
        jPanelpayerLayout.setHorizontalGroup(
            jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelpayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonpayer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelpayerLayout.createSequentialGroup()
                        .addComponent(jLabeltimbre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldtimbre, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                    .addGroup(jPanelpayerLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelpayerLayout.createSequentialGroup()
                        .addComponent(jLabelmontanttva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldtotalttc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldmontanttva))))
                .addContainerGap())
        );
        jPanelpayerLayout.setVerticalGroup(
            jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelpayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelpayerLayout.createSequentialGroup()
                        .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltimbre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtimbre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmontanttva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmontanttva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelpayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldtotalttc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelpayerLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonpayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonfacture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonfacture.setForeground(new java.awt.Color(0, 0, 102));
        jButtonfacture.setText("Facture");

        jButtonbonlivraison.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonbonlivraison.setForeground(new java.awt.Color(0, 0, 102));
        jButtonbonlivraison.setText("Bon de Livraison");
        jButtonbonlivraison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbonlivraisonActionPerformed(evt);
            }
        });

        jButtondevis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtondevis.setForeground(new java.awt.Color(0, 0, 102));
        jButtondevis.setText("Devis");
        jButtondevis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondevisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonbonlivraison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtondevis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonfacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jButtonbonlivraison)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtondevis)
                .addGap(11, 11, 11)
                .addComponent(jButtonfacture))
        );

        javax.swing.GroupLayout jPanelventeLayout = new javax.swing.GroupLayout(jPanelvente);
        jPanelvente.setLayout(jPanelventeLayout);
        jPanelventeLayout.setHorizontalGroup(
            jPanelventeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jButtonsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelventeLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jPanelpayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelventeLayout.setVerticalGroup(
            jPanelventeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelventeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelventeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelpayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelinfoarticle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Code Article");

        jTextFieldcode.setEditable(false);
        jTextFieldcode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldcode)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldcode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Designation");

        jTextFielddesignation.setEditable(false);
        jTextFielddesignation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFielddesignation)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFielddesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prix Vente");

        jTextFieldprixvente.setEditable(false);
        jTextFieldprixvente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldprixvente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldprixvente)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldprixvente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Stock");

        jTextFieldstock.setEditable(false);
        jTextFieldstock.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldstock)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldstock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/details 32.png"))); // NOI18N
        jLabel19.setText("Details Article");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("TVA");

        jTextFieldtva.setEditable(false);
        jTextFieldtva.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldtva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldtva)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldtva, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonpanier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonpanier.setForeground(new java.awt.Color(0, 0, 102));
        jButtonpanier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/add basket 32.png"))); // NOI18N
        jButtonpanier.setText("Ajouter au panier");
        jButtonpanier.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButtonpanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpanierActionPerformed(evt);
            }
        });

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelquantite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelquantite.setForeground(new java.awt.Color(102, 0, 102));
        jLabelquantite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelquantite.setText("Quantite");

        jTextFieldquantite.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldquantite.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldquantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldquantiteActionPerformed(evt);
                jTextFieldquantiteActionListener(evt);
            }
        });
        jTextFieldquantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldquantiteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldquantiteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldquantiteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabelquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldquantite)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelinfoarticleLayout = new javax.swing.GroupLayout(jPanelinfoarticle);
        jPanelinfoarticle.setLayout(jPanelinfoarticleLayout);
        jPanelinfoarticleLayout.setHorizontalGroup(
            jPanelinfoarticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelinfoarticleLayout.createSequentialGroup()
                .addGroup(jPanelinfoarticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonpanier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelinfoarticleLayout.setVerticalGroup(
            jPanelinfoarticleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelinfoarticleLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonpanier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jLabelchercher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelchercher.setForeground(new java.awt.Color(153, 0, 0));
        jLabelchercher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelchercher.setText("Chercher");

        jTextFieldchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldchercherActionPerformed(evt);
            }
        });
        jTextFieldchercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldchercherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldchercherKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldchercherKeyTyped(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBoxarticle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxarticle.setMaximumRowCount(10000);
        jComboBoxarticle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jComboBoxarticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxarticleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxarticleMouseEntered(evt);
            }
        });
        jComboBoxarticle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboBoxarticleComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxarticleComponentShown(evt);
            }
        });
        jComboBoxarticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxarticleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/list 32.png"))); // NOI18N
        jLabel2.setText("Liste des Articles");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jComboBoxarticle, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBoxtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxtype.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jComboBoxtype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxtypeKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Type");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorie");

        jComboBoxcategorie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxcategorie.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jComboBoxcategorie.setPreferredSize(new java.awt.Dimension(85, 23));
        jComboBoxcategorie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxcategorieKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxcategorie, 0, 258, Short.MAX_VALUE)
                    .addComponent(jComboBoxtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxcategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxtype, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/panier 64.png"))); // NOI18N
        jLabel6.setText("Details Vente  (PANIER)");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/caisse 30.png"))); // NOI18N
        jLabel4.setText("Caissier");

        jLabelnomvendeur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelnomvendeur.setForeground(new java.awt.Color(0, 102, 102));
        jLabelnomvendeur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelnomvendeur, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelnomvendeur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabeldate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeldate.setForeground(new java.awt.Color(153, 0, 51));
        jLabeldate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendeurs/date time 48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeldate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBarvendeur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuvendeurfichier.setForeground(new java.awt.Color(153, 0, 0));
        jMenuvendeurfichier.setText("Fichier");
        jMenuvendeurfichier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuvendeurfichier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuvendeurfichier.setPreferredSize(new java.awt.Dimension(80, 20));

        jMenubonretour.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenubonretour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenubonretour.setText("Bon de Retour");
        jMenuvendeurfichier.add(jMenubonretour);

        jMenurecette.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenurecette.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenurecette.setText("Recette");
        jMenuvendeurfichier.add(jMenurecette);

        jMenudeconnecter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenudeconnecter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenudeconnecter.setText("Deconnecter");
        jMenuvendeurfichier.add(jMenudeconnecter);

        jMenuBarvendeur.add(jMenuvendeurfichier);

        jMenuvendeurediter.setForeground(new java.awt.Color(153, 0, 0));
        jMenuvendeurediter.setText("Editer");
        jMenuvendeurediter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuvendeurediter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuvendeurediter.setPreferredSize(new java.awt.Dimension(80, 20));

        jMenuediterbon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuediterbon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuediterbon.setText("Bon de Livraison");
        jMenuvendeurediter.add(jMenuediterbon);

        jMenuediterdevis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuediterdevis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuediterdevis.setText("Devis");
        jMenuvendeurediter.add(jMenuediterdevis);

        jMenuediterfacture.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuediterfacture.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuediterfacture.setText("Facture");
        jMenuediterfacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuediterfactureActionPerformed(evt);
            }
        });
        jMenuvendeurediter.add(jMenuediterfacture);

        jMenuBarvendeur.add(jMenuvendeurediter);

        jMenuvendeurimprimer.setForeground(new java.awt.Color(153, 0, 0));
        jMenuvendeurimprimer.setText("Imprimer");
        jMenuvendeurimprimer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuvendeurimprimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuvendeurimprimer.setPreferredSize(new java.awt.Dimension(80, 20));

        jMenuItembonlivraison.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItembonlivraison.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItembonlivraison.setText("Bon de Livraison");
        jMenuvendeurimprimer.add(jMenuItembonlivraison);

        jMenudevis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenudevis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenudevis.setText("Devis");
        jMenuvendeurimprimer.add(jMenudevis);

        jMenufacture.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenufacture.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenufacture.setText("Facture");
        jMenufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenufactureActionPerformed(evt);
            }
        });
        jMenuvendeurimprimer.add(jMenufacture);

        jMenuBarvendeur.add(jMenuvendeurimprimer);

        setJMenuBar(jMenuBarvendeur);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelchercher, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldchercher))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelinfoarticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldchercher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelchercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(291, 291, 291))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelinfoarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(82, 82, 82))
                    .addComponent(jPanelvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void resizejtable(JTable table){
        table.getColumnModel().getColumn(0).setPreferredWidth(130);
        table.getColumnModel().getColumn(1).setPreferredWidth(350);
        table.getColumnModel().getColumn(2).setPreferredWidth(160);
        table.getColumnModel().getColumn(3).setPreferredWidth(80);
        table.getColumnModel().getColumn(4).setPreferredWidth(90);
        table.getColumnModel().getColumn(5).setPreferredWidth(150);
        table.getColumnModel().getColumn(6).setMinWidth(0);
        table.getColumnModel().getColumn(6).setMaxWidth(0);
        table.getColumnModel().getColumn(6).setWidth(0);
        
    }
    
    
    private void jComboBoxarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxarticleActionPerformed
        // TODO add your handling code here:
        clearinfoarticle();
        fillinfoarticle();
        //jComboBoxarticle.removeAllItems();       
        //fillcombo(); 
        
    }//GEN-LAST:event_jComboBoxarticleActionPerformed

    private void jComboBoxarticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxarticleMouseClicked
        // TODO add your handling code here:
   jComboBoxarticle.removeAllItems();       
   fillcombo();            
    }//GEN-LAST:event_jComboBoxarticleMouseClicked

    private void jComboBoxarticleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxarticleComponentShown
        // TODO add your handling code here:
   jComboBoxarticle.removeAllItems();       
   fillcombo();  
    }//GEN-LAST:event_jComboBoxarticleComponentShown

    private void jComboBoxarticleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxarticleMouseEntered
        // TODO add your handling code here:
   //jComboBoxarticle.removeAllItems();       
  // fillcombo();       
    }//GEN-LAST:event_jComboBoxarticleMouseEntered

    private void jComboBoxarticleComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxarticleComponentHidden
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxarticleComponentHidden

    private void jButtonpanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpanierActionPerformed
        // TODO add your handling code here:
        // create an array of objects to set the row data
filltable();
clearinfoarticle();
        
    }//GEN-LAST:event_jButtonpanierActionPerformed

 
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldquantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldquantiteActionPerformed
        // TODO add your handling code here:
     //if (jTextFieldquantite.getText().equals("")) jButtonpanier.setEnabled(false);
      //else jButtonpanier.setEnabled(true); 
        //jTextFieldquantite.addActionListener(jComboBoxtype);
        
       
        
                    //    if (q.equals("")) jButtonpanier.setEnabled(false);
              //  else jButtonpanier.setEnabled(true);
        
    }//GEN-LAST:event_jTextFieldquantiteActionPerformed

    private void jTextFieldquantiteActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldquantiteActionListener
        // TODO add your handling code here:
        
             //  System.out.println("OK");
       if(jTextFieldquantite.getText().length()>0){
        int x=Integer.parseInt(jTextFieldquantite.getText());
        int y=Integer.parseInt(jTextFieldstock.getText());
    jButtonpanier.setEnabled((x>0) && (x<=y));
        }     
    }//GEN-LAST:event_jTextFieldquantiteActionListener

    private void jTextFieldquantiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldquantiteKeyTyped
        // TODO add your handling code here:
       /* 
             //   System.out.println("OK");
          String q=jTextFieldquantite.getText().toString();
       if (q.equals("")) jButtonpanier.setEnabled(false);
              else jButtonpanier.setEnabled(true); */
    }//GEN-LAST:event_jTextFieldquantiteKeyTyped

    private void jButtonbonlivraisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbonlivraisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonbonlivraisonActionPerformed

    private void jButtondevisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondevisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtondevisActionPerformed

    private void jButtonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupprimerActionPerformed
        // TODO add your handling code here:
                        // i = the index of the selected row
     DefaultTableModel model =   (DefaultTableModel)jTabledetailsvente.getModel();
                int i = jTabledetailsvente.getSelectedRow();
                if(i >= 0){
                    // remove a row from jtable
                    model.removeRow(i);
                }
                else{
              InputStream in = null;
         try {
             in = new FileInputStream(new File("SON\\stop.wav"));
         } catch (FileNotFoundException ex) {
             Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
         }
              AudioStream son = null;
         try {
             son = new AudioStream(in);
         } catch (IOException ex) {
             Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
         }
              AudioPlayer.player.start(son);
              
              JOptionPane.showMessageDialog(this," Aucune ligne a supprimer"); 
                }
        
                if (jTabledetailsvente.getRowCount()==0) {
                    
                    jButtonpayer.setEnabled(false);
                    jButtonbonlivraison.setEnabled(false);
                    jButtondevis.setEnabled(false);
                    jButtonfacture.setEnabled(false);
                    
                    jButtonsupprimer.setEnabled(false);
                    
                    
                    
                    
                    
                }
                
  Double f=sommetva(jTabledetailsvente);
  String str;
  str=setvirgule(f,3);

  jTextFieldmontanttva.setText(str.replaceAll(",", ".") + "  TND");
   f=sommetotal(jTabledetailsvente);
   str=setvirgule(f,3);
   jTextFieldtotalttc.setText(str.replaceAll(",", ".")+"  TND");
               
                
    }//GEN-LAST:event_jButtonsupprimerActionPerformed

    public String setvirgule(Double d, int n){
   
    NumberFormat virgule = NumberFormat.getInstance(); 
    virgule.setMinimumFractionDigits(n);       //Nb de Digit mini 
    virgule.setMaximumFractionDigits(n);       //Nb de Digit Maxi 
    return(virgule.format(d));  //Formatage str="12.45" 
     
    }
    
    
    
    
    private void jTextFieldchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldchercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldchercherActionPerformed

    private void jTextFieldtimbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtimbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtimbreActionPerformed

    private void jTextFieldmontanttvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmontanttvaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldmontanttvaActionPerformed

    private void jButtonpayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpayerActionPerformed
    ajoutervente();
    }//GEN-LAST:event_jButtonpayerActionPerformed

    
    public void ajoutervente() {
        
                try {
            // TODO add your handling code here:
            Connection con;
            PreparedStatement pst;
            Statement st;
            ResultSet rs;
            int cv=0;
      
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", ""); 
            String strdate = new SimpleDateFormat("dd/MM/YYYY",Locale.FRENCH).format(new Date());
            String strtime = new SimpleDateFormat("HH:mm:ss",Locale.FRENCH).format(new Date());
            Double montanttva =Double.parseDouble(jTextFieldmontanttva.getText().toString().replaceAll("  TND", ""));
            Double totalttc= Double.parseDouble(jTextFieldtotalttc.getText().toString().replaceAll("  TND", ""));
            String username = jLabelnomvendeur.getText().toString();
            String query = "insert into vente(date,time,montanttva,totalttc,username) values(?,?,?,?,?)";           
            pst = con.prepareStatement(query);
            pst.setString(1,strdate);
            pst.setString(2,strtime);
            pst.setDouble(3, montanttva);
            pst.setDouble(4,totalttc);
            pst.setString(5,username);
            int res=pst.executeUpdate();

            query = "select codevente from vente where username='"+username+"' AND date='"+strdate+"' AND time= '"+strtime+"'";
            st=con.createStatement();
            rs=st.executeQuery(query);
            while(rs.next()){cv=rs.getInt(1); }
                      
 int rows=jTabledetailsvente.getRowCount();          
for(int row = 0; row<rows; row++)
{
  int codearticle=Integer.parseInt(jTabledetailsvente.getValueAt(row, 0).toString());
  int quantite=Integer.parseInt(jTabledetailsvente.getValueAt(row, 4).toString());  
 
  
query="insert into detailsvente(codevente,codearticle,quantite) values(?,?,?)";
pst=con.prepareStatement(query);
pst.setInt(1,cv);
pst.setInt(2,codearticle);
pst.setInt(3, quantite);
res=pst.executeUpdate();



query="update article set stock= stock -"+quantite+"  where codearticle="+codearticle;
pst=con.prepareStatement(query);
pst.executeUpdate();
         } 
      
cleartable(jTabledetailsvente);
reset();


       } catch (SQLException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
 
    
    
    
    private void jTabledetailsventeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabledetailsventeKeyPressed
        // TODO add your handling code here:   
modify();        
    }//GEN-LAST:event_jTabledetailsventeKeyPressed

    private void jTabledetailsventeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabledetailsventeKeyTyped
        // TODO add your handling code here:
   modify();
        
    }//GEN-LAST:event_jTabledetailsventeKeyTyped

    private void jTabledetailsventeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabledetailsventeKeyReleased
        // TODO add your handling code here:
        modify();
    }//GEN-LAST:event_jTabledetailsventeKeyReleased

    private void jTextFieldquantiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldquantiteKeyReleased
        // TODO add your handling code here:
       if(jTextFieldquantite.getText().length()>0){
        int x=Integer.parseInt(jTextFieldquantite.getText());
        int y=Integer.parseInt(jTextFieldstock.getText());
    jButtonpanier.setEnabled((x>0) && (x<=y));
        }
    }//GEN-LAST:event_jTextFieldquantiteKeyReleased

    private void jTextFieldquantiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldquantiteKeyPressed
        // TODO add your handling code here:
           if(jTextFieldquantite.getText().length()>0){
        int x=Integer.parseInt(jTextFieldquantite.getText());
        int y=Integer.parseInt(jTextFieldstock.getText());
    jButtonpanier.setEnabled((x>0) && (x<=y));
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          filltable();
      // Enter was pressed. Your code goes here.
   }
        }   
    }//GEN-LAST:event_jTextFieldquantiteKeyPressed

    private void jTextFieldchercherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldchercherKeyPressed
        // TODO add your handling code here:
            jComboBoxarticle.removeAllItems();
    fillcombo();
    }//GEN-LAST:event_jTextFieldchercherKeyPressed

    private void jTextFieldchercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldchercherKeyReleased
        // TODO add your handling code here:
    jComboBoxarticle.removeAllItems();
    fillcombo();
    }//GEN-LAST:event_jTextFieldchercherKeyReleased

    private void jTextFieldchercherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldchercherKeyTyped
        // TODO add your handling code here:
    jComboBoxarticle.removeAllItems();
    fillcombo();
    }//GEN-LAST:event_jTextFieldchercherKeyTyped

    private void jMenufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenufactureActionPerformed
       
        
        
        
        
        
        MessageFormat header = new  MessageFormat("Facture num: "+5);
        MessageFormat footer = new  MessageFormat("Page{0,number,integer}");

        try {
            // TODO add your handling code here:

            jTabledetailsvente.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (PrinterException ex) {
            Logger.getLogger(vendeur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenufactureActionPerformed

    private void jMenuediterfactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuediterfactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuediterfactureActionPerformed

    private void jComboBoxcategorieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxcategorieKeyPressed
        // TODO add your handling code here:
        fillcombocat();
    }//GEN-LAST:event_jComboBoxcategorieKeyPressed

    private void jComboBoxtypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxtypeKeyPressed
        // TODO add your handling code here:
        fillcombotype();
    }//GEN-LAST:event_jComboBoxtypeKeyPressed
      public void fillcombotype(){
     Connection con;
        Statement st;
        ResultSet rs;
            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String query ="SELECT nomtype from type ";
            rs=st.executeQuery(query);
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxtype.addItem(rs.getString("nomtype"));
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }     
    } 
 
public void fillcombocat(){
     Connection con;
        Statement st;
        ResultSet rs;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String query ="SELECT nomcategorie from categorie ";
 
            rs=st.executeQuery(query);
            
            
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxcategorie.addItem(rs.getString("nomcategorie"));
                
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }    
        
    }
           
      
    
    public void modify(){
                      DefaultTableModel model =   (DefaultTableModel)jTabledetailsvente.getModel();
                int i = jTabledetailsvente.getSelectedRow();
  

                if(i >= 0){
                         
            int b=Integer.parseInt(jTextFieldstock.getText());
          
            
            
           
            if(jTabledetailsvente.getValueAt(i, 4).toString().length()==0)
            {
            JOptionPane.showMessageDialog(this, " inserer une valeur correcte !!!");

            
            jTabledetailsvente.editCellAt(i, 4);
            jTabledetailsvente.setSurrendersFocusOnKeystroke(true);
            jTabledetailsvente.getEditorComponent().requestFocus();
            
            
            }
            else
            {
                Integer a=Integer.parseInt(jTabledetailsvente.getValueAt(i, 4).toString());
                if (a<=0)  { JOptionPane.showMessageDialog(this, "SVP inserer une valeur    >  0 ");
 
                             jTabledetailsvente.editCellAt(i, 4);
                             jTabledetailsvente.setSurrendersFocusOnKeystroke(true);
                             jTabledetailsvente.getEditorComponent().requestFocus();  
                            }
                
                else  if (a>b)  {JOptionPane.showMessageDialog(this, " Stock insuffisant  !!!  max disponible =  "+b);
                

                               jTabledetailsvente.editCellAt(i, 4);
                               jTabledetailsvente.setSurrendersFocusOnKeystroke(true);
                               jTabledetailsvente.getEditorComponent().requestFocus();
                               }
                else 
                {              
              //Double a=Double.parseDouble(jTabledetailsvente.getValueAt(i, 4).toString());
              Double p=Double.parseDouble(jTextFieldprixvente.getText());
              
              Double s=a*p;
              String pch=setvirgule(s,3).replaceAll(",", ".");
              
              jTabledetailsvente.setValueAt(pch, i, 5);
              jTabledetailsvente.setValueAt(s, i, 6);
                }
           Double f=sommetva(jTabledetailsvente);
     String str;
     str = setvirgule(f,3);  //Formatage str="12.45" 
 jTextFieldmontanttva.setText(str.replaceAll(",", ".") + "  TND");
  f=sommetotal(jTabledetailsvente);
 str=setvirgule(f,3);
 jTextFieldtotalttc.setText(str.replaceAll(",", ".")+"  TND");
                 
                }
                }
    }
    
    
    
public boolean exist(String x, JTable table) {
    // Get row and column count
    int rowCount = table.getRowCount();
   // int colCount = table.getColumnCount();
boolean z=false;
    for (int i = 0; i < rowCount; i++) {
            if (x.equals(table.getValueAt(i, 0).toString()) ) 
            {z= true;  }
        }  
    return z;
}

public int position(String x, JTable table) {
    // Get row and column count
    int i;
    int rowCount = table.getRowCount();
   // int colCount = table.getColumnCount();
   int z=-1;
    for (i = 0; i < rowCount; i++) {
            if (x.equals(table.getValueAt(i, 0).toString()) ) 
            {z= i;  }
        }  
    return z;
}



public Double sommetva( JTable table) {
    // Get row and column count
    int rowCount = table.getRowCount();
   // int colCount = table.getColumnCount();

Double s;
        s = 0.0;
    for (int i = 0; i < rowCount; i++) {
        String tva=table.getValueAt(i, 2).toString();
        Double a=Double.parseDouble(tva.replaceAll(",", "."));
        Double b=Double.parseDouble(table.getValueAt(i, 3).toString().substring(0,table.getValueAt(i, 3).toString().length()-1 ));
        Double c=Double.parseDouble(table.getValueAt(i, 4).toString());        
        s+=a*(b/100)*c;
        }    
    return s;
}    

public Double sommetotal(JTable table)
    {
    int rowCount = table.getRowCount();   
    Double s,a;
        s = 0.0;
    for (int i = 0; i < rowCount; i++) {
        a=Double.parseDouble(table.getValueAt(i, 6).toString());   
        s+=a;
        }        
     return s;   
    }
    ///////////////////////   



public Statement stconnect() throws SQLException{
 
         Connection con;
        Statement st = null;
        try{
        con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
        st=con.createStatement(); 
        }
        catch(Exception e){
            System.out.println("error connect base");
        }
        return st;
}

    public void fillinfoarticle(){
     
        Statement st;
        ResultSet rs;
        
        try{
          st=stconnect();
           
            String des=(String)jComboBoxarticle.getSelectedItem();
            String query="SELECT * from article WHERE designationarticle='"+des+"'";
            rs=st.executeQuery(query);
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jTextFieldcode.setText(rs.getString("codearticle"));
                jTextFielddesignation.setText(rs.getString("designationarticle"));
                jTextFieldprixvente.setText(rs.getString("prixvente"));                          
                jTextFieldtva.setText(rs.getString("tva")+"%");
                jTextFieldstock.setText(rs.getString("stock"));
                //String q=jTextFieldquantite.getText();       
            }
            

            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }    
        
    }
  
    
 public void cleartable(JTable table){
DefaultTableModel model =(DefaultTableModel)table.getModel();
                while (table.getRowCount() > 0) {
                    ((DefaultTableModel) table.getModel()).removeRow(0);
                }
                /*
     for(int i=0;i<model.getRowCount();i++){
 model.removeRow(i);
 System.out.println(i);
     }*/             
    }   
    
    public void reset()
    {
     jButtonpayer.setEnabled(false);
     jButtondevis.setEnabled(false);
     jButtonbonlivraison.setEnabled(false);
     jButtonfacture.setEnabled(false);
     jTextFieldtotalttc.setText("0.000"+"  TND");
     jTextFieldmontanttva.setText("0.000"+"  TND");
        
    }        
    
    ////////////////////////    
   public void clearinfoarticle(){
       
                jTextFieldcode.setText("");
                jTextFielddesignation.setText("");
                jTextFieldprixvente.setText("");
                jTextFieldtva.setText("");
                jTextFieldstock.setText(""); 
                jTextFieldquantite.setText("");
                jButtonpanier.setEnabled(false);
   } 

  public void fillcombo(){
     Connection con;
        Statement st;
        ResultSet rs;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            String cat=(String)jComboBoxcategorie.getSelectedItem();
            String type=(String)jComboBoxtype.getSelectedItem();
            String r=jTextFieldchercher.getText().replaceAll(" ","%");
            String query ;//="SELECT * from article";
            
            if (r.equals(""))
            query="SELECT * from article WHERE typearticle='"+type+"' AND categoriearticle='"+cat+"'";
            
            else query="SELECT * from article WHERE designationarticle LIKE '%"+r+"%'";
            
            rs=st.executeQuery(query);
            
            
            //jComboBoxarticle.removeAllItems();
            while(rs.next()){
               // System.out.println(rs.getString(1)+"|"+rs.getString(2));
                //Int des=rs.getInt("codearticle");
                jComboBoxarticle.addItem(rs.getString("designationarticle"));
                
            }
            //con.close();
        }
            catch(Exception e){
                    
                System.out.println("Erreur de connexion a  la base");
            
                    }    
        
    }
     
     
 public void filltable(){
     
        DefaultTableModel model =   (DefaultTableModel)jTabledetailsvente.getModel();
        Object[] row = new Object[7];
        
                row[0] = jTextFieldcode.getText();
                row[1] = jTextFielddesignation.getText();                
                Double a=Double.parseDouble(jTextFieldprixvente.getText());
                Double b=Double.parseDouble(jTextFieldtva.getText().substring(0,jTextFieldtva.getText().length()-1 ));                
                Double ht=a/(1+b/100);                
                row[2] = setvirgule(ht,3).replaceAll(",", ".");
                row[3] = jTextFieldtva.getText(); 
                Integer j=Integer.parseInt(jTextFieldstock.getText());
                if(jTextFieldquantite.getText().length()>0)
                {
                Integer i=Integer.parseInt(jTextFieldquantite.getText());
                if (i<=0)  { JOptionPane.showMessageDialog(this, "SVP inserer une valeur    >  0 ");}
                
                else  if (i>j)  {JOptionPane.showMessageDialog(this, " Stock insuffisant  !!!  max disponible =  "+j);}
                else 
                {row[4] = jTextFieldquantite.getText();
                
                row[5] = setvirgule(Double.parseDouble(jTextFieldquantite.getText()) *  Double.parseDouble(jTextFieldprixvente.getText()),3).replaceAll(",", "."); 
  
                row[6] = (Double.parseDouble(jTextFieldquantite.getText()) *  Double.parseDouble(jTextFieldprixvente.getText())); 
                
                //row[5]=row[5].toString().replaceAll(",",".");
                //row[5]=row[5].toString().replaceAll(" ", "+");
                // add row to the model                
                if (!exist(row[0].toString(),jTabledetailsvente))
                model.addRow(row);
                else {
                    JOptionPane.showMessageDialog(this, " article existe deja dans le panier MODIFIER la quantite svp  !!!");
                  jTabledetailsvente.editCellAt(position(row[0].toString(),jTabledetailsvente), 4);
                  jTabledetailsvente.setSurrendersFocusOnKeystroke(true);
                  jTabledetailsvente.getEditorComponent().requestFocus();
                    
                    
                    
                }
Double f=sommetva(jTabledetailsvente);
String str;
 str = setvirgule(f,3);
 jTextFieldmontanttva.setText(str.replaceAll(",", ".") + "  TND");
 f=sommetotal(jTabledetailsvente);

 str=setvirgule(f,3);
 jTextFieldtotalttc.setText(str.replaceAll(",", ".")+"  TND");
//}catch(ParseException pe) { 
//System.out.println("parse : " + pe); 
//} 
        jTextFieldquantite.setText("");
        jButtonpayer.setEnabled(true) ;
        jButtonbonlivraison.setEnabled(true);
        jButtondevis.setEnabled(true);
        jButtonfacture.setEnabled(true);
        jButtonsupprimer.setEnabled(true);
        
        //jTextFieldmontanttva.setText(str + "  TND");
        
    }
   }   
 }     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new vendeur("").setVisible(true);
                 
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbonlivraison;
    private javax.swing.JButton jButtondevis;
    private javax.swing.JButton jButtonfacture;
    private javax.swing.JButton jButtonpanier;
    private javax.swing.JButton jButtonpayer;
    private javax.swing.JButton jButtonsupprimer;
    private javax.swing.JComboBox jComboBoxarticle;
    private javax.swing.JComboBox jComboBoxcategorie;
    private javax.swing.JComboBox jComboBoxtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelchercher;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JLabel jLabelmontanttva;
    private javax.swing.JLabel jLabelnomvendeur;
    private javax.swing.JLabel jLabelquantite;
    private javax.swing.JLabel jLabeltimbre;
    private javax.swing.JMenuBar jMenuBarvendeur;
    private javax.swing.JMenuItem jMenuItembonlivraison;
    private javax.swing.JMenuItem jMenubonretour;
    private javax.swing.JMenuItem jMenudeconnecter;
    private javax.swing.JMenuItem jMenudevis;
    private javax.swing.JMenuItem jMenuediterbon;
    private javax.swing.JMenuItem jMenuediterdevis;
    private javax.swing.JMenuItem jMenuediterfacture;
    private javax.swing.JMenuItem jMenufacture;
    private javax.swing.JMenuItem jMenurecette;
    private javax.swing.JMenu jMenuvendeurediter;
    private javax.swing.JMenu jMenuvendeurfichier;
    private javax.swing.JMenu jMenuvendeurimprimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelinfoarticle;
    private javax.swing.JPanel jPanelpayer;
    private javax.swing.JPanel jPanelvente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledetailsvente;
    private javax.swing.JTextField jTextFieldchercher;
    private javax.swing.JTextField jTextFieldcode;
    private javax.swing.JTextField jTextFielddesignation;
    private javax.swing.JTextField jTextFieldmontanttva;
    private javax.swing.JTextField jTextFieldprixvente;
    private javax.swing.JTextField jTextFieldquantite;
    private javax.swing.JTextField jTextFieldstock;
    private javax.swing.JTextField jTextFieldtimbre;
    private javax.swing.JTextField jTextFieldtotalttc;
    private javax.swing.JTextField jTextFieldtva;
    // End of variables declaration//GEN-END:variables
}
