/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hichem
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        filltable();
        resetbutton();
        clearuser();
          jButtonenregistreruser.setEnabled(false);
          jButtonmodifieruser.setEnabled(false);
          jButtonsupprimeruser.setEnabled(false);
          jButtonimprimeruser.setEnabled(true);
          jButtonexceluser.setEnabled(true);
          jButtonnouveauuser.setText("Nouveau");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeleditionuser = new javax.swing.JLabel();
        jLabelisteuser = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextFieldrechercheuser = new javax.swing.JTextField();
        jLabelrechercheuser = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonfirstuser = new javax.swing.JButton();
        jButtonbackuser = new javax.swing.JButton();
        jButtonnextuser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonlastuser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonnouveauuser = new javax.swing.JButton();
        jButtonmodifieruser = new javax.swing.JButton();
        jButtonsupprimeruser = new javax.swing.JButton();
        jButtonenregistreruser = new javax.swing.JButton();
        jButtonimprimeruser = new javax.swing.JButton();
        jButtonexceluser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelisteuser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldnomuser = new javax.swing.JTextField();
        jTextFieldpassuser = new javax.swing.JTextField();
        jComboBoxtypeuser = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1347, 824));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabeleditionuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabeleditionuser.setForeground(new java.awt.Color(0, 0, 153));
        jLabeleditionuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeleditionuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users/edit utilisateurs 64.png"))); // NOI18N
        jLabeleditionuser.setText("Edition des utilistauers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeleditionuser, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeleditionuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelisteuser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelisteuser.setForeground(new java.awt.Color(0, 51, 204));
        jLabelisteuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelisteuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users/utilisateurs 64.png"))); // NOI18N
        jLabelisteuser.setText("Liste d'Utilisateurs");

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setPreferredSize(new java.awt.Dimension(251, 49));

        jTextFieldrechercheuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldrechercheuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrechercheuserActionPerformed(evt);
            }
        });
        jTextFieldrechercheuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheuserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldrechercheuserKeyTyped(evt);
            }
        });

        jLabelrechercheuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelrechercheuser.setForeground(new java.awt.Color(102, 0, 51));
        jLabelrechercheuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelrechercheuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/search 32.png"))); // NOI18N
        jLabelrechercheuser.setText("Recherche");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelrechercheuser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldrechercheuser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelrechercheuser, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addComponent(jTextFieldrechercheuser)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonfirstuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonfirstuser.setForeground(new java.awt.Color(0, 102, 102));
        jButtonfirstuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/first 32.png"))); // NOI18N
        jButtonfirstuser.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonfirstuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfirstuserActionPerformed(evt);
            }
        });

        jButtonbackuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonbackuser.setForeground(new java.awt.Color(0, 102, 102));
        jButtonbackuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/back 32.png"))); // NOI18N
        jButtonbackuser.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonbackuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackuserActionPerformed(evt);
            }
        });

        jButtonnextuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonnextuser.setForeground(new java.awt.Color(0, 102, 102));
        jButtonnextuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/next 32.png"))); // NOI18N
        jButtonnextuser.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonnextuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnextuserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deplacement");

        jButtonlastuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonlastuser.setForeground(new java.awt.Color(0, 102, 102));
        jButtonlastuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/last 32.png"))); // NOI18N
        jButtonlastuser.setPreferredSize(new java.awt.Dimension(50, 23));
        jButtonlastuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlastuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonfirstuser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonbackuser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonnextuser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonlastuser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonfirstuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonbackuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonnextuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonlastuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButtonnouveauuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonnouveauuser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonnouveauuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/new 24.png"))); // NOI18N
        jButtonnouveauuser.setText("Nouveau");
        jButtonnouveauuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonnouveauuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnouveauuserActionPerformed(evt);
            }
        });

        jButtonmodifieruser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonmodifieruser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonmodifieruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/update 24.png"))); // NOI18N
        jButtonmodifieruser.setText("Modifier");
        jButtonmodifieruser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonmodifieruser.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonmodifieruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodifieruserActionPerformed(evt);
            }
        });

        jButtonsupprimeruser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonsupprimeruser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonsupprimeruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/delete 24.png"))); // NOI18N
        jButtonsupprimeruser.setText("Supprimer");
        jButtonsupprimeruser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonsupprimeruser.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonsupprimeruser.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonsupprimeruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsupprimeruserActionPerformed(evt);
            }
        });

        jButtonenregistreruser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonenregistreruser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonenregistreruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/save 24.png"))); // NOI18N
        jButtonenregistreruser.setText("Enregistrer");
        jButtonenregistreruser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonenregistreruser.setPreferredSize(new java.awt.Dimension(75, 23));
        jButtonenregistreruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonenregistreruserActionPerformed(evt);
            }
        });

        jButtonimprimeruser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonimprimeruser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonimprimeruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/print 24.png"))); // NOI18N
        jButtonimprimeruser.setText("Imprimer");
        jButtonimprimeruser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonexceluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonexceluser.setForeground(new java.awt.Color(0, 51, 51));
        jButtonexceluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/articles/excel 24.png"))); // NOI18N
        jButtonexceluser.setText("Excel");
        jButtonexceluser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonnouveauuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonmodifieruser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonsupprimeruser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonenregistreruser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonimprimeruser, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
            .addComponent(jButtonexceluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonnouveauuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonenregistreruser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonmodifieruser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonsupprimeruser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonexceluser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonimprimeruser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users/user 64.png"))); // NOI18N
        jLabel1.setText("Info Utilisateur");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTablelisteuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablelisteuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Utilsateur", "Mot de passe", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablelisteuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablelisteuserMouseClicked(evt);
            }
        });
        jTablelisteuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTablelisteuserFocusGained(evt);
            }
        });
        jTablelisteuser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTablelisteuserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTablelisteuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablelisteuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablelisteuserKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablelisteuser);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Utilisateur");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mot de passe");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Type");

        jTextFieldnomuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldnomuser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextFieldpassuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldpassuser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jComboBoxtypeuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxtypeuser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USER", "ADMIN" }));
        jComboBoxtypeuser.setPreferredSize(new java.awt.Dimension(6, 20));
        jComboBoxtypeuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxtypeuserMouseClicked(evt);
            }
        });
        jComboBoxtypeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtypeuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldpassuser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jComboBoxtypeuser, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldnomuser))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldnomuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldpassuser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxtypeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelisteuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelisteuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldrechercheuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrechercheuserActionPerformed
        // TODO add your handling code here:
        String x=jTextFieldrechercheuser.getText();
        if (x.length()>0 ){
            cleartable(jTablelisteuser);
            filltable(x);
            resetdeplacement();

        } else {
            cleartable(jTablelisteuser);
            filltable();
            resetdeplacement();

        }

    }//GEN-LAST:event_jTextFieldrechercheuserActionPerformed

      public void filltable(){
     
        cleartable(jTablelisteuser);
        
        DefaultTableModel model =   (DefaultTableModel)jTablelisteuser.getModel();
        Object[] row = new Object[9];
        
        
        
        
        Connection con;
        Statement st,st1;
        ResultSet rs,rs1;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            String query1;
            String query="select * from users";
                rs = st.executeQuery(query);
                while(rs.next()){
                     row[0] = rs.getString(1);
                     row[1] = rs.getString(2);
                     row[2] = rs.getString(3);

                     model.addRow(row);
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    }  

public void filltable(String x){
     
        cleartable(jTablelisteuser);
        
        DefaultTableModel model =   (DefaultTableModel)jTablelisteuser.getModel();
        Object[] row = new Object[9];
        
        
        
        
        Connection con;
        Statement st,st1;
        ResultSet rs,rs1;
       

            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            st=con.createStatement();
            st1=con.createStatement();
            String query1;
            String query="select * from users WHERE username LIKE '%"+x+"%' OR password LIKE '%"+x+"%'";
                rs = st.executeQuery(query);
                while(rs.next()){
                     row[0] = rs.getString(1);
                     row[1] = rs.getString(2);
                     row[2] = rs.getString(3);
                     model.addRow(row);
                }
                    }
            catch(Exception e){
                
                System.out.println("ERROR DATABASE"+e);
            }
   
    }
    
          
      
      
      
    
    
    private void jTextFieldrechercheuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheuserKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldrechercheuserKeyPressed

    private void jTextFieldrechercheuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheuserKeyReleased
        // TODO add your handling code here:
        String x=jTextFieldrechercheuser.getText();
        if (x.length()>0 ){
            cleartable(jTablelisteuser);
            filltable(x);
            clearuser();
            resetbutton();
            resetdeplacement();
            jTablelisteuser.setEnabled(true);
            jButtonmodifieruser.setEnabled(false);
            jButtonsupprimeruser.setEnabled(false);

        } else {
            cleartable(jTablelisteuser);
            filltable();
            clearuser();
            jTablelisteuser.setEnabled(true);
            resetbutton();
            resetdeplacement();
            jButtonmodifieruser.setEnabled(false);
            jButtonsupprimeruser.setEnabled(false);
        }

    }//GEN-LAST:event_jTextFieldrechercheuserKeyReleased

     public void resetdeplacement(){
        jButtonbackuser.setEnabled(true);
        jButtonfirstuser.setEnabled(true);
        jButtonnextuser.setEnabled(true);
        jButtonlastuser.setEnabled(true);
        
        
        
    }   
    
    
    
    private void jTextFieldrechercheuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldrechercheuserKeyTyped
        // TODO add your handling code here:

        String x=jTextFieldrechercheuser.getText();
        if (x.length()>0 ){
            cleartable(jTablelisteuser);
            filltable();
       

        } else {
            cleartable(jTablelisteuser);
            filltable();

        }
    }//GEN-LAST:event_jTextFieldrechercheuserKeyTyped

    
 public void cleartable(JTable table){
DefaultTableModel model =(DefaultTableModel)table.getModel();
     


                while (table.getRowCount() > 0) {
                    ((DefaultTableModel) table.getModel()).removeRow(0);
                }
                /*
     for(int i=0;i<model.getRowCount();i++){
 model.removeRow(i);
 System.out.println(i);
     }*/
                
    }   
 
 public void clearuser(){
     jTextFieldnomuser.setText("");
     jTextFieldpassuser.setText("");
     
     
 }
 boolean rowselected=false;
 int index;
 
    
    private void jButtonfirstuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfirstuserActionPerformed
        // TODO add your handling code here:

        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelisteuser.getModel();
        index=jTablelisteuser.getSelectedRow();
        if (index<=0){
            jTablelisteuser.setRowSelectionInterval(0,0);
            fillinfouser();
            jButtonbackuser.setEnabled(false);
            jButtonfirstuser.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelisteuser.setRowSelectionInterval(0, 0);
            fillinfouser();
            jButtonbackuser.setEnabled(false);
            jButtonfirstuser.setEnabled(false);
            jButtonnextuser.setEnabled(true);
            jButtonlastuser.setEnabled(true);
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonfirstuserActionPerformed

    private void jButtonbackuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackuserActionPerformed
        // TODO add your handling code here:
        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelisteuser.getModel();
        index=jTablelisteuser.getSelectedRow();
        if (index<=0){
            jTablelisteuser.setRowSelectionInterval(0,0);
            fillinfouser();
            jButtonbackuser.setEnabled(false);
            jButtonfirstuser.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelisteuser.setRowSelectionInterval(index-1, index-1);
            fillinfouser();
            jButtonnextuser.setEnabled(true);
            jButtonlastuser.setEnabled(true);
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonbackuserActionPerformed

    private void jButtonnextuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnextuserActionPerformed
        // TODO add your handling code here:

        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelisteuser.getModel();
        index=jTablelisteuser.getSelectedRow();

        if(index==jTablelisteuser.getRowCount()-1){
            jButtonnextuser.setEnabled(false);
            jButtonlastuser.setEnabled(false);
        }
        if (index==-1){
            jTablelisteuser.setRowSelectionInterval(0,0);
            fillinfouser();
            jButtonbackuser.setEnabled(false);
            jButtonfirstuser.setEnabled(false);

        }

        else {
            if(index==jTablelisteuser.getRowCount()-1){
                jButtonnextuser.setEnabled(false);
                jButtonlastuser.setEnabled(false);}else
            {
                //model.moveRow(index, index, index+1);
                jTablelisteuser.setRowSelectionInterval(index+1, index+1);
                fillinfouser();
                jButtonbackuser.setEnabled(true);
                jButtonfirstuser.setEnabled(true);
            }
        }

        //jTablelistearticle.
        //jTablelistearticle.setSelectionBackground(Color.yellow);

    }//GEN-LAST:event_jButtonnextuserActionPerformed

    private void jButtonlastuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlastuserActionPerformed
        // TODO add your handling code here:
        if (rowselected==false){
            rowselected=true;
        }
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel) jTablelisteuser.getModel();
        index=jTablelisteuser.getSelectedRow();
        if (index<=0){
            jTablelisteuser.setRowSelectionInterval(jTablelisteuser.getRowCount()-1,jTablelisteuser.getRowCount()-1);
            fillinfouser();
            jButtonbackuser.setEnabled(true);
            jButtonfirstuser.setEnabled(true);
            jButtonnextuser.setEnabled(false);
            jButtonlastuser.setEnabled(false);
        }
        else{
            //model.moveRow(index, index, index-1);
            jTablelisteuser.setRowSelectionInterval(jTablelisteuser.getRowCount()-1, jTablelisteuser.getRowCount()-1);
            fillinfouser();
            jButtonbackuser.setEnabled(true);
            jButtonfirstuser.setEnabled(true);
            jButtonnextuser.setEnabled(false);
            jButtonlastuser.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonlastuserActionPerformed

    private void jButtonnouveauuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnouveauuserActionPerformed
        // TODO add your handling code here:
        if(jButtonnouveauuser.getText().equals("Nouveau")){
            jButtonenregistreruser.setEnabled(true);
            jButtonmodifieruser.setEnabled(false);
            jButtonsupprimeruser.setEnabled(false);
            jButtonimprimeruser.setEnabled(false);
            jButtonexceluser.setEnabled(false);
            jButtonnouveauuser.setText("Annuler");
            clearuser();
            jTablelisteuser.setEnabled(false);
        }
        else
        resetbutton();
    }//GEN-LAST:event_jButtonnouveauuserActionPerformed

    public void resetbutton(){
if(jButtonnouveauuser.getText().equals("Annuler")) {
          jButtonenregistreruser.setEnabled(false);
          jButtonmodifieruser.setEnabled(false);
          jButtonsupprimeruser.setEnabled(false);
          jButtonimprimeruser.setEnabled(true);
          jButtonexceluser.setEnabled(true);
          jButtonnouveauuser.setText("Nouveau");
          clearuser();
          jTablelisteuser.setEnabled(true);
  
        }    
     
    }    
    
    
    
    
    private void jButtonmodifieruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodifieruserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =   (DefaultTableModel)jTablelisteuser.getModel();

        int i=jTablelisteuser.getSelectedRow();
        if(i>-1){
            jButtonmodifieruser.setEnabled(true);

            int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de modifier cet utilisateur","Modifier Utilisateur",JOptionPane.YES_NO_OPTION);

            if(res==0){
                System.out.println("Utilisateur modifie");

            }
        }else {JOptionPane.showMessageDialog(this, "Selectionner un utilisateur SVP");}

    }//GEN-LAST:event_jButtonmodifieruserActionPerformed

    
 public void fillinfouser(){
    DefaultTableModel model =   (DefaultTableModel)jTablelisteuser.getModel();
    
     int i=jTablelisteuser.getSelectedRow();
     if(i>-1){
     jTextFieldnomuser.setText(model.getValueAt(i,0).toString());
     jTextFieldpassuser.setText(model.getValueAt(i,1).toString());
     jComboBoxtypeuser.setSelectedItem(model.getValueAt(i,2).toString());

     
          jTablelisteuser.setEnabled(true);
          resetbutton();
          jButtonmodifieruser.setEnabled(true);
          jButtonsupprimeruser.setEnabled(true);

     }
}   
    
    
    
    
    private void jButtonsupprimeruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsupprimeruserActionPerformed
        // TODO add your handling code here:

        int res=JOptionPane.showConfirmDialog(null, "Etes Vous sure de Supprimer cet Utilisateur","Supprimer Utilisateur",JOptionPane.YES_NO_OPTION);
        if(res==0){
            System.out.println("Utilisateur Supprime");

        }

    }//GEN-LAST:event_jButtonsupprimeruserActionPerformed

    private void jButtonenregistreruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonenregistreruserActionPerformed
        // TODO add your handling code here:
     
        String nom=jTextFieldnomuser.getText();
 
        String pass=jTextFieldpassuser.getText();
        String type=jComboBoxtypeuser.getSelectedItem().toString();

        try {
            // TODO add your handling code here:
            Connection con;
            PreparedStatement pst;
            Statement st;
            ResultSet rs;

            con=DriverManager.getConnection("jdbc:mysql://localhost/mayarinfodb", "root", "");
            String query = "insert into users(username,password,type) values(?,?,?)";
            pst = con.prepareStatement(query);
            pst.setString(1,nom);
            pst.setString(2,pass);
            pst.setString(3, type);

            int res=pst.executeUpdate();

        }
        catch (Exception e){
            System.out.println("ERROR DATABASE:  " +e);
        }

        //cleartable(jTablelistearticle);
        //filltable();

        filltable();
       
        resetbutton();
        //cleararticle();
        jTextFieldnomuser.setText("");
        jButtonenregistreruser.setEnabled(false);
        jButtonnouveauuser.setEnabled(true);
        jTablelisteuser.setEnabled(true);

    }//GEN-LAST:event_jButtonenregistreruserActionPerformed

    private void jTablelisteuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablelisteuserMouseClicked
        // TODO add your handling code here:
        fillinfouser();

    }//GEN-LAST:event_jTablelisteuserMouseClicked

    private void jTablelisteuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablelisteuserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablelisteuserFocusGained

    private void jTablelisteuserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTablelisteuserAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTablelisteuserAncestorAdded

    private void jTablelisteuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelisteuserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablelisteuserKeyPressed

    private void jTablelisteuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablelisteuserKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model =   (DefaultTableModel)jTablelisteuser.getModel();

        int i=jTablelisteuser.getSelectedRow();
  
        jTextFieldnomuser.setText(model.getValueAt(i,0).toString());
        jTextFieldpassuser.setText(model.getValueAt(i,1).toString());
 
       
        jComboBoxtypeuser.setSelectedItem(model.getValueAt(i,2).toString());

        jTablelisteuser.setEnabled(true);
        resetbutton();
        jButtonmodifieruser.setEnabled(true);
        jButtonsupprimeruser.setEnabled(true);

    }//GEN-LAST:event_jTablelisteuserKeyReleased

    private void jComboBoxtypeuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxtypeuserMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jComboBoxtypeuserMouseClicked

    private void jComboBoxtypeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtypeuserActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxtypeuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbackuser;
    private javax.swing.JButton jButtonenregistreruser;
    private javax.swing.JButton jButtonexceluser;
    private javax.swing.JButton jButtonfirstuser;
    private javax.swing.JButton jButtonimprimeruser;
    private javax.swing.JButton jButtonlastuser;
    private javax.swing.JButton jButtonmodifieruser;
    private javax.swing.JButton jButtonnextuser;
    private javax.swing.JButton jButtonnouveauuser;
    private javax.swing.JButton jButtonsupprimeruser;
    private javax.swing.JComboBox jComboBoxtypeuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabeleditionuser;
    private javax.swing.JLabel jLabelisteuser;
    private javax.swing.JLabel jLabelrechercheuser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelisteuser;
    private javax.swing.JTextField jTextFieldnomuser;
    private javax.swing.JTextField jTextFieldpassuser;
    private javax.swing.JTextField jTextFieldrechercheuser;
    // End of variables declaration//GEN-END:variables
}
