/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mayarinformatique;

import administrateurs.administrateur;
import sun.audio.*;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vendeurs.vendeur;

/**
 *
 * @author Hichem
 */
public class Mayarinfo extends javax.swing.JFrame {

    /**
     * Creates new form Mayarinfo
     */
    public Mayarinfo() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabellogin = new javax.swing.JLabel();
        jLabelpass = new javax.swing.JLabel();
        jButtonconnect = new javax.swing.JButton();
        jTextFielduser = new javax.swing.JTextField();
        jCheckBoxpass = new javax.swing.JCheckBox();
        jButtonannuler = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mayar info POS by Hichem Lamine");
        setResizable(false);

        jLabellogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(0, 102, 102));
        jLabellogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabellogin.setText("Utilisateur");

        jLabelpass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelpass.setForeground(new java.awt.Color(0, 102, 102));
        jLabelpass.setText("Mot de passe");

        jButtonconnect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonconnect.setForeground(new java.awt.Color(102, 0, 102));
        jButtonconnect.setText("Login");
        jButtonconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconnectActionPerformed(evt);
            }
        });

        jTextFielduser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFielduser.setForeground(new java.awt.Color(0, 102, 102));

        jCheckBoxpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxpass.setForeground(new java.awt.Color(102, 0, 102));
        jCheckBoxpass.setText("Afficher Mot de passe");
        jCheckBoxpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxpassActionPerformed(evt);
            }
        });

        jButtonannuler.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonannuler.setForeground(new java.awt.Color(102, 0, 102));
        jButtonannuler.setText("Cancel");
        jButtonannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonannulerActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(0, 102, 102));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelpass, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonconnect, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addComponent(jTextFielduser, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxpass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFielduser)
                    .addComponent(jLabellogin, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBoxpass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField)
                            .addComponent(jLabelpass, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonannuler, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxpassActionPerformed
        // TODO add your handling code here:
      if (jCheckBoxpass.isSelected()) {jPasswordField.setEchoChar((char)0); }
      else {
          
          jPasswordField.setEchoChar('*');
      }
        
    }//GEN-LAST:event_jCheckBoxpassActionPerformed

    private void jButtonannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonannulerActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonannulerActionPerformed

    private void jButtonconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconnectActionPerformed
        // TODO add your handling code here:
        Connection con;
        Statement st;
        ResultSet rs;
        String query;
        
        try {
           
       // Class.forName("com.mysql.jdbc.Driver");
         //DriverManager.getDrivers();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mayarinfodb", "root", "");
            st=con.createStatement();
            String u=jTextFielduser.getText();
            String p=jPasswordField.getText();
            query= "SELECT * from users WHERE username='"+u+"' AND password='"+p+"'" ;
            rs=st.executeQuery(query);
            
          if (u.equals("")|| p.equals("")) {
              
              InputStream in=new FileInputStream(new File("SON\\stop.wav"));
              AudioStream son=new AudioStream(in);
              AudioPlayer.player.start(son);
              
              JOptionPane.showMessageDialog(this," Veuiller saisir votre nom et votre mot de passe SVP"); 
              
          jTextFielduser.setText("");
          jPasswordField.setText("");
          //AudioPlayer.player.stop();
          }
          else
          
        if (rs.next()){
           String type =rs.getString("type");
           //System.out.println(type);
       if (type.equals("USER")){
      //   System.out  .println(rs.getString(1) + "|"+rs.getString("password")+"|"+rs.getString("type"));
                setVisible(false);
                vendeur vend=new vendeur(u);
                vend.setVisible(true);
       }
       else{
                setVisible(false);
                administrateur ad=new administrateur();
                ad.setVisible(true);  
       }
          
        } else {
            
            InputStream in=new FileInputStream(new File("SON\\stop.wav"));
            AudioStream son=new AudioStream(in); 
            AudioPlayer.player.start(son);
            JOptionPane.showMessageDialog(this," nom d'utilisateur ou mot de passe incorrect");
            jTextFielduser.setText("");
            jPasswordField.setText("");
        }}
        catch (Exception ex) {
            //Logger.getLogger(Mayarinfo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Erreur de connexion a  la base");
        }
        
        
    }//GEN-LAST:event_jButtonconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mayarinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mayarinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mayarinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mayarinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Mayarinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonannuler;
    private javax.swing.JButton jButtonconnect;
    private javax.swing.JCheckBox jCheckBoxpass;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFielduser;
    // End of variables declaration//GEN-END:variables

}
